### ISSUE TITLE
Taller 3 Condicionales - Punto 4

### ISSUE THREAD

**Issue by Elioric** [codingupmyfuture/bootcamplinuxpython#101]
Buenas tardes,

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/9ff6d463-1de7-4223-9534-ecb9efb9b819)

Tengo la inquietud de si éste ejercicio debe retornar la suma de los cuadrados de los catetos o el valor de la hipotenusa del  triángulo. Debido a que la suma de los cuadrados es de la forma a<sup>2</sup> + b<sup>2</sup>, pero la hipotenusa de un triángulo es la raíz cuadrada del valor calculado anteriormente hipotenusa = sqrt(a<sup>2</sup> + b<sup>2</sup>).

Calcular suma de los cuadrados:
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/c07bb606-61fe-4d78-beec-ae4d55c3367a)

Devolver hipotenusa:
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/82a8734b-d93e-4a12-bc52-629834fd9a2a)

**Comment by EstebanaOrozco** [comment]
Deberían corregir la redacción del taller porque quienes aún no han hecho el taller van a tener la misma confusión. Yo asumí que era el cálculo de la hipotenusa y recibí mala calificación.
