### ISSUE TITLE
Revisión Pregunta 7 - Taller 4 (Bucles)

### ISSUE THREAD

**Issue by JonathanProf** [codingupmyfuture/bootcamplinuxpython#102]
Buenas tardes, quisiera solicitar corrección a la respuesta esperada por el calificador para el ejercicio 7. 
El enunciado es el siguiente:

`Escribir dentro del cuerpo de la función function la lógica que permita imprimir los objetos de un diccionario ordenado por sus keys. Adicionalmente, usted deberá retornar una lista con las keys ordenadas del diccionario. Su código debe seguir las siguientes condiciones:`

`1. Puede asumir que todas las keys son strings.`
`2. Las keys deben estar ordenadas por orden alfabético.`
`3. El formato a imprimir es {}: {}`

Luego de resolver el ejercicio para el siguiente diccionario 
`{ 'language': "Python", 'Number': 89, 'track': "High level", 'Name': 'Softserve', 'ids': [1, 2, 3] }`

Obtuve la siguiente respuesta `(['ids', 'language', 'Name', 'Number', 'track'],)`, pero el bot me calificó malo y presentó la siguiente respuesta como base de calificación `(['Name', 'Number', 'ids','language', 'track'],)`.

Considero que la respuesta que genera el bot como referencia no se estaría cumpliendo la condición 2 de orden alfabético.

Gracias.

**Comment by Elioric** [comment]
Tengo la misma inquietud. No lo he enviado, pero sí me generó la duda de que alfabéticamente las mayúsculas tienen prevalencia sobre las minúsculas en la manera que se expresa en programación. Sin embargo, el ejercicio es claro en que debería hacerse alfabéticamente, por lo que no debería importar si son mayúsculas o minúsculas. Lo entendería de esa manera

**Comment by JoseJulianMosqueraFuli** [comment]
En Python y otros lenguajes de programación, cuando comparas cadenas de texto (como palabras o frases), se utilizan reglas para determinar el orden en el que se colocan en una lista o en una ordenación. Estas reglas siguen el orden en el que se encuentran los caracteres en un conjunto internacional llamado Unicode.

En Unicode, las letras mayúsculas se definen antes que las letras minúsculas. Esto significa que, al ordenar o comparar cadenas de texto, las letras mayúsculas siempre se colocarán antes que las letras minúsculas.

**Comment by keljozap** [comment]
Hola chicos buenas tardes. Esto se debe a que la función sort o sorted, tiene en cuenta los valores ASCII de los caracteres. Y en estos las mayúsculas vienen primero que las minúsculas.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/749f0323-5a02-4f7d-af2d-a6e0e0a4f547)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/c13b9c0e-7240-428b-a84d-7fd338f53e33)

**Comment by Elioric** [comment]
Buenas tardes, @JoseJulianMosqueraFuli  @keljozap según la información expuesta sobre el trato que reciben las letras según Unicode, entonces sería ordenarlas según Unicode debido a la calificación que pone en OP? O sí se haría la corrección para que sea ordenado alfabéticamente independientemente de que sea mayúsculas o minúsculas?

Muchas gracias

**Comment by keljozap** [comment]
Hola! @Elioric si usaste la función sorted, esta lo hace automáticamente con el unicode así que no habría que corregir nada. Recordemos que el ejercicio pretende evaluar bucles y el fuerte de la lógica se encontraría allí, la parte de ordenado es algo adicional (una cáscara) ya que en el módulo anterior ya habíamos visto como ordenar iterables, no tendría sentido hacer un código que haga esto en vez de usar una función existente que nos simplifique el problema.

**Comment by JonathanProf** [comment]
Buenas tardes, entonces como conclusión para este punto ¿sería solo aplicar sort e ignorar el requerimiento del literal 2? 
Creo que la confusión radica más desde el punto del análisis porque en papel y sin usar ningún método de listas como `sort`, y respetando el orden alfabético, 'ids' y 'language' si irían antes que 'Name' y 'Number'. Pero aplicando sort naturalmente el computador ordena basado en la tabla ASCII por la diferencia que existe en los caracteres en mayúscula y en minúscula.

**Comment by keljozap** [comment]
Hola buenas tardes. No es sort, ya que sort no puede usarse para los diccionarios, es el método sorted que aplica para cualquier iterable. La solución es aplicar le método sorted que internamente toma en cuenta el valor unicode de los caracteres ASCII. En los cursos de programación es importante aplicar la lógica a los problemas para así encontrar la mejor solución a estos (solución en la lógica programable), en este caso como lo has descrito anteriormente "alfabeticamente" para el computador es tomar el orden de los caracteres unicodes, al final todos son ceros y unos en programación de bajo nivel y esto haría la respuesta correcta.

**Comment by JonathanProf** [comment]
Muchas gracias por la aclaración
