### ISSUE TITLE
Taller 2 - punto 3 Mala redacción de ejercicio 

### ISSUE THREAD

**Issue by deivish** [codingupmyfuture/bootcamplinuxpython#104]
En el ejercicio se solicita generar la logica para hallar el Volumen de la superficie y el Área de un cilindro.

pero según la consulta que he echo no existe el Volumen de la superficie no es un concepto matematico común, en este caso solo seria Volumen y  Área de superficie.

Y para hallar el Volumen y el Área se usa el radio y en el ejercicio nos dan como parametros el radian y creo entender que ese valor hace referencia a el radio. Ya que tampoco se usa el radian en la formula.

Para aclarar y tener en cuenta y si me equivoco podrian correjirme por favor, ya que no se si es mala redaccion o interpretación del ejercicio aun así eso genera confusión.

**Comment by JoseJulianMosqueraFuli** [comment]
Hola @deivish, el tema lo tocaron antes en este issue https://github.com/codingupmyfuture/bootcamplinuxpython/issues/99, se agregaron las formulas y un compañero aclaro lo del valor.
