### ISSUE TITLE
Taller # 3 pregunta 3

### ISSUE THREAD

**Issue by alejandrazapatap** [codingupmyfuture/bootcamplinuxpython#105]
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/7007dc3f-7ebd-4e43-99fe-8b3a77921f09)

Tengo duda por la calificacion de este ejercicio ya que el párametro que se le esta pasando esta dentro de la lista, entonces se debe contar como True y no como False.

![Captura de pantalla 2023-09-20 071435](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/7e40165b-4a9e-46e9-ac5e-f98657558ff7)

**Comment by JoseJulianMosqueraFuli** [comment]
Creo que es por esta razon:
- Verifique que la variable no sea nula, si es nula retornar False.

**Comment by alejandrazapatap** [comment]
ah si ya lo veo compañero gracias😁
