### ISSUE TITLE
Taller # 3 pregunta 6

### ISSUE THREAD

**Issue by alejandrazapatap** [codingupmyfuture/bootcamplinuxpython#106]
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/992938fd-47d6-4fcb-9ce2-cc05cd22d2b2)

Tengo duda ya que al hacer la evaluacion el bot muestra cero como string pero en sus parametros tambien cero esta como int
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/a1822f91-5c48-4aaf-bdcc-3a21d52f9b6f)
pero en la respuesta de control esta como int 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/f131e037-615f-4694-b5f0-18726d70559a)

**Comment by JoseJulianMosqueraFuli** [comment]
Parece que la respuesta esperada es un string, y estas retornando un entero.
No estoy seguro si es por esta razón:
- Retornar "0" si el último dígito es 0.

**Comment by alejandrazapatap** [comment]
si es que esa es mi duda por en la respuesta de control el bot si lo evalua como entero

**Comment by JoseJulianMosqueraFuli** [comment]
Curiosamente, a mi este punto no me evaluo ninguna condición con 0, así que no puedo brindarte mayor soporte, Yo lo aborde bajo la condición, que comente anteriormente.
