### ISSUE TITLE
Taller #4 bucles - ejercicio 09 [Error en respuesta esperada]

### ISSUE THREAD

**Issue by melenabelt** [codingupmyfuture/bootcamplinuxpython#108]
Según el ejercicio se debe retornar el número de veces que aparece la letra en la frase proporcionada, pero el ejercicio tiene el return de ejemplo de la siguiente manera:

<img width="141" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/48cf3dea-3bc9-4c8d-b1eb-66f3d68a2944">

Esto puede llegar a ser confuso, ya que no se debe retornar un diccionario.

**Comment by villarrealjk** [comment]
Hola @melenabelt,

Si puede parecer confuso pero eso es una guía de lo que se debe retornar, recuerda también que en clases el profe nos ha dicho que podemos nombrar a las variables como queramos (sin embargo no es lo correcto en un ambiente productivo), quizás cuando construyeron el ejercicio se fue esa palabra pero el resultado que debe retornar el la función el # de veces que aparece la letra en la cadena.

**Comment by melenabelt** [comment]
No tiene sentido tiene nombrar como diccionario a un elemento que no es key-value. Es confuso y más cuando todos los return se han nombrado correctamente. Posiblemente es un error de tipeo, pero los issues también se crearon para problemas que pueden generar confusiones 😊

**Comment by JoseJulianMosqueraFuli** [comment]
Hola @keljozap, comprendo tu preocupación acerca de la claridad de las instrucciones. Es cierto que algunas personas pueden encontrar este tipo de ejercicios un poco confusos. 
__Una posible solución :__ Podría ser ofrecer ejercicios opcionales o proporcionar una explicación más detallada sobre la importancia de la comprensión lectora en la programación en ese punto(s).
__*Nota*__: Por que veo que las personas tiene muchas dudas sobre algunos puntos, y la idea es podernos ayudar todos.

Nada que discutir en las buenas prácticas de codigo para que sea más legible, en última instancia, el objetivo principal es que el código funcione correctamente, sea extensible y sea comprensible para quienes lo lean.

Si alguien tiene alguna otra sugerencia o comentario, estaré encantado de leerlo. ¡Saludos!

**Comment by keljozap** [comment]
Hola @JoseJulianMosqueraFuli yo no tenia la duda, de hecho estaba explicando el por qué de algunas instrucciones como en este caso, sin embargo gracias por tu aporte.
