### ISSUE TITLE
Error en respuesta del bot - Taller Condicionales

### ISSUE THREAD

**Issue by maurorpo** [codingupmyfuture/bootcamplinuxpython#109]
El bot me retorna el siguiente error:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/19668689/864bdf19-6ef8-4eec-b054-c618b59d6f37)

Que puede estar generandolo? no tengo una acción como la que dice el bot

**Comment by JoseJulianMosqueraFuli** [comment]
Parece que: 
En alguna parte del codigo estas intentando realizar la conversion de `'False'` a float, ya `'False'` no es una representación válida de un número decimal. Asegúrate de verificar que las cadenas/datos que estás convirtiendo a flotantes sean números válidos.

**Comment by Elioric** [comment]
Valida que no estés devolviendo un valor booleano en una función que debería devolver un valor numérico

**Comment by juanm-ot** [comment]
![bug](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/103142667/cd66a630-3166-4dec-a4e0-bb0f7e881fb9)
Saludos, @luisvasv-teck

Puedes, por favor, validar que esta pasando acá. Siguiendo las instrucciones líneas arriba y revisando también paso a paso el código a través de pruebas de escritorio, valide que todo lo que estuviera en formato string estuviera casteado a numérico. Aun así, persiste el error. ¿Podrías darme alguna luz de como abordarlo o revisar si capaz pasa algo internamente? 

Gracias.

**Comment by JoseJulianMosqueraFuli** [comment]
Hola, talvez pueda ser de ayuda lo que dice jose-92 en este issue, https://github.com/codingupmyfuture/bootcamplinuxpython/issues/118.
