### ISSUE TITLE
Error Faltas Asistencia

### ISSUE THREAD

**Issue by luisfejaramillor** [codingupmyfuture/bootcamplinuxpython#11]
Buenas noches,

Espero se encuentren muy bien. Escribo con la intención de informar que yo he asistido a todas las sesiones que se han dado, y que he estado durante las dos horas de cada sesión. Por ende, me preocupa que yo termine siendo expulsado del curso por alguna falla relacionada al momento del registro o uso del aplicativo "Zoom", ya que aparezco con una falta y con solo 132 minutos a la fecha.

Mi computadora tiene instalado como sistema operativo Linux - Ubuntu, el cual me estaba poniedo problemas para actualizar la versión de Zoom a la requerida por ustedes. Justo hoy, 08 de agosto, actualizé correctamente  zoom a la última versión 5.15.5.

Quedo atento a sus comentarios o inquietudes.

Saludos,

Luis Felipe Jaramillo Restrepo
CEL 3217294299

**Comment by CristianMongar** [comment]
Hola Luis.  Yo utilizo linux como sistema operativo y tambien presenté algunos inconvenientes con la versión de zoom.  Lo que hice para solucionalo fue descargar la versión de escritorio directamente desde la pagina oficial de zoom la cual permite instalar en todos los sistemas operativos.

**Comment by Angie0312** [comment]
Buenas tardes,
En la sesión del martes 8 de agosto no pude acceder correctamente a zoom con el link que llego a mi correo debido a que el link estaba malo.
Casi al final de la clase logre acceder con un nuevo link que se compartió. En este caso ¿Mi asistencia si se contó?

**Comment by luisvasv-teck** [comment]
Estos temas, por favor escribió dliza@softserveinc.com
