### ISSUE TITLE
Error respuesta del Bot- Punto 4- Condicionales

### ISSUE THREAD

**Issue by juliansernave** [codingupmyfuture/bootcamplinuxpython#110]
Cordial saludo @luisvasvv @luisvasv-teck 

El BOT me bota la respuesta NO SE PUEDE RESOLVER desde el primer intento. Cuando lo pruebo en mi pc con esos mismos parámetros veo que sí funciona bien 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/b84ea8e2-790e-4c45-af5e-0a466e5cc5a8)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/042acf15-d461-4ad7-8ff8-4c9fee0ba8f9)

Adicionalmente el ejercicio pide la hipotenusa y en el caso en el que el bot recibe 0.5 y 7, debería dar la raíz cuadrada de 49 y no 49.... caso que también considero que tengo bueno ya que mi respuesta es 7..... 

Quedo atento, muchas gracias 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/fe5217aa-8cbb-40d3-ae7a-0b15d7f6adac)

**Comment by Josjisut** [comment]
Habría que verificar el por que se esta generando el error, eso lo puedes verificar revisando dos cosas, la primera es que en el documento un poco mas arriba de donde esta ese cuadro que mandaste te muestra por que se genero el error, revisar ese código de error que te genera el bot y con el verificar donde puede estar generándose ese error.

**Comment by juliansernave** [comment]
Gracias @Josjisut, justamente sale vacío 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/d2240adc-7ad3-4771-85fc-1b1a108b21a3)

**Comment by Josjisut** [comment]
Tendrías que revisar el código pues lo mas probable es que este teniendo un problema con los valores negativos que esta generando ese error.

**Comment by keljozap** [comment]
Buenos días a todos chicos. Esto ya se había resuelto en este issue, por favor revísenlo y si siguen con dudas coméntenme nuevamente en este hilo.

https://github.com/codingupmyfuture/bootcamplinuxpython/issues/101

Para revisar el error en tu código @juliansernave tendrías que compartirnos tu código para revisar.

**Comment by juliansernave** [comment]
@keljozap gracias por tu respuesta. Quedo atento a cómo quieras que comparta mi código, yo hice mis pruebas locales de nuevo y no me falla con los parámetros del bot como puedes ver en el primer comentario 

Con respecto al issue https://github.com/codingupmyfuture/bootcamplinuxpython/issues/101, la verdad la respuesta no tiene sentido, ya que la hipotenusa es la raiz cuadrada de la suma de los catetos y en el ejercicio dice claramente devolver la hipotenusa, no la suma de los catetos unicamente

**Comment by keljozap** [comment]
Hola @juliansernave lo puedes compartir por acá si no tienes lío no problem. Respecto al issue #101 estoy respondiendo lo siguiente:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/43a7a0d7-60f8-4076-8192-72cfaf0d6866)

Donde confirmo que la hipotenusa ES LA RAIZ DE LA SUMA DE LOS CATETOS ELEVADA AL CUADRADO y aunque el ejercicio está (como lo dijo el compañero que levantó el issue primero) indicando que se debe devolver el valor de la hipotenusa en la sección de return (usando incorrectamente el término hipotenusa), en la descripción de este se esta pidiendo (la suma de los cuadrados de los catetos de un triángulo) SIN SACAR RAÍZ CUADRADA, lo cual no lo convierte en hipotenusa, es correcto, pero esto es lo que se pide.

NOTA: El ejercicio es confuso dado que se pide una suma de catetos en la descripción pero en la sección de return se indica que debe ser la hipotenusa, dado que ya había sido señalado anteriormente y que como resolución se indicó que debe retornarse LA SUMA DE LOS CUADRADOS DE LOS CATETOS, como se indica en la descripción del ejercicio.

Sabemos que es confuso y ya lo había sido para otro compañero, motivo por el que levantó el issue y se índico cual debía ser el tratamiento a seguir, para resolver el ejercicio de una forma que el control lo indique correcto.

Espero con esto resolver la duda.

**Comment by juliansernave** [comment]
@keljozap prefiero que revises el codigo con mi correo jsern@softserveinc.com :) 

Honestamente la respuesta no tiene mucho sentido, si se sabe y se identificó un error en el enunciado debería corregirse

Se pidieron dos cosas diferentes: por un lado la suma del cuadrado de los catetos y por otro se solicita la hipotenusa, tal cual como lo mencionas. Si es confuso, de verdad y con mucho respeto creo que la aclaración debió ser antes de que alguna persona enviara el taller.

**Comment by aquirozg** [comment]
Hola! Tengo el mismo problema que @juliansernave ...el bot me califica mal algunos resultados de este punto pero validando con mi código veo que mi código sí arroja los valores que debería 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/7189b781-460b-4c74-8a79-fa7f4502dc46)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/5e27da62-d01a-46f6-824b-9f65f10482e3)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/a2be41bd-863f-4d25-9198-0479d09df2d7)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/f4e4b8d7-5e03-411b-ac6b-f7dec04a02df)

@keljozap @luisvasv-teck 

Quedo atenta a cómo podemos revisar mi código, me cuentan si lo mando por un correo, un chat, o cómo :) gracias!!

**Comment by keljozap** [comment]
Hola @aquirozg veo en tu código que estas usando la función type, en clase aprendimos otro método que puede ayudarte con la solución de este problema, ya que type puede devolverte en algunos casos un objeto completamente nuevo.

Quedo atenta.

**Comment by aquirozg** [comment]
@keljozap Entiendo lo que mencionas sobre el type, pero mi pregunta es por qué el bot califica mal este punto, teniendo en cuenta que cuando ingreso los parámetros que el bot utiliza, mi código arroja el mismo resultado que el bot. Adjunto nuervamente los pantallazos sin el type para no confundirte y señalando los parámetros de entrada y los resultados en cada imagen. 
Repito, quedo atenta a cómo podemos revisar mi código, me cuentan si lo mando por un correo, un chat, o cómo.
Gracias! :)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/b4091c2f-1472-4664-b64c-bec7011c9fbc)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/86749a0d-dc4a-4872-86d2-36eb265112df)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/dd8aea20-edc7-4fd8-b2db-64c03c42980a)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/423f55d8-a840-4dd6-886c-b708f394cbf4)
