### ISSUE TITLE
NO SE PUEDE RESOLVER- Punto 7 condicionales 

### ISSUE THREAD

**Issue by juliansernave** [codingupmyfuture/bootcamplinuxpython#111]
Buen día @luisvasvv @luisvasv-teck 

En el último parámetro evaluado en el punto 7 de condicionales me aparece NO SE PUEDE RESOLVER, sin embargo cuando pruebo localmente sí obtengo una respuesta 

Cuando veo la respuesta del bot considero que tiene un error ya que el error 3 es si el last_name no es string, sin embargo, a nivel de los parámetros evaluados AMBOS parámetros no son string por lo cual imprimí "error 2 y 3" porque ambas se cumplen 

Te pido encarecidamente que puedas revisar este caso y muchas gracias! 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/71ef82f4-95fa-4d9a-be4b-9769f20aa5f3)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/2ed4c287-d222-4d0e-9dff-6c8edd5ff345)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/486192ad-8205-4ce7-b1e7-95ee7281af59)

**Comment by Josjisut** [comment]
Habría que verificar que error te esta arrojando sin embargo revisando de forma superficial la respuesta "2 y 3" no es una respuesta valida para el bot, pues si miras el ejemplo que da el punto sobre la respuesta esperada: 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/113815029/476d88d9-0588-4121-ba6e-b27ee8d08e79)
 
Ahí puedes verificar que las respuestas esperadas son "True/2/3" por lo que cualquier respuesta diferente a esas la va  a tomar como error.

**Comment by juliansernave** [comment]
Gracias @Josjisut, lo que mencionas es cierto, sin embargo en ningun escenario se pedía el caso que ninguno de los dos fuera string. Y la respuesta del bot (3) es sólo como si sólo last_name no fuera string

**Comment by Josjisut** [comment]
Si, lo mas probable es que se deba aplicar jerarquía y que solo se tome el primer caso y de ahí ya no contemple las otras condiciones

**Comment by EstebanaOrozco** [comment]
Si tienes bien los "if" solo se debería aplicar la primer condición y devolver el valor 2, pues no cumple con la primera condición a evaluar, tal como dijo @Josjisut.

**Comment by juliansernave** [comment]
@EstebanaOrozco según la jerarquía que mencionas, el resultado sería 2. Sin embargo la respuesta del bot arroja 3. 

Yo contemplé un solo condicional en el caso que se cumplieran ambas condiciones. Más que una duda, creo que al ejercicio le faltó claridad en este escenario

**Comment by keljozap** [comment]
Buenos dias chicos. @juliansernave el enunciado nos indica que 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/0f5f778b-2625-4baf-80bb-56c207a6c190)

"Si ambas variables son strings", es decir, puede llegar a presentarse el caso de que NO LO SEAN. Motivo por el cual los parámetros first_name y last_name pueden tomar cualquier valor, siendo cualquier valor un boolean, un integer, o un None siendo este un tipo de dato válido. Ustedes deben tener en cuenta CUALQUIER TIPO DE ENTRADA ya que el bot está evaluando no sólo números y strings.

Espero haber contestado la pregunta.

**Comment by juliansernave** [comment]
@keljozap muchas gracias por tu respuesta! 

La verdad sigue sin quedar claro porque en ninguna parte el enunciado detalla el escenario "En caso que AMBAS variables no sean string"

Por ejemplo que diga... "En caso de que first name y last name no sean string, imprima error 4"...

Por eso no tiene sentido imprimir sólo el error 3 ya que este error alude una sola variable

**Comment by keljozap** [comment]
Hola @juliansernave. Recuerda que este es un ejercicio de condicionales, y en el enunciado nos están indicando que AMBOS deben ser Strings, es decir, ambas variables deben cumplir las condiciones (ósea es una condición AND). El enunciado también indica que se debe hacer si no se cumplen TODAS las condiciones.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/cd0884ea-7eeb-413b-9ca1-40223e26ce0f)

Y respecto a tu pregunta, al ser una condición AND, basta con que una de las dos sea false para que la expresión completa sea evaluada como false, es por esto que no tiene sentido poner una condición adicional donde se contemple que ambas son false.

Adjunto la tabla de verdad de AND

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/dd7b920a-0506-486b-9ce2-cc49ed5bfca1)

**Comment by juliansernave** [comment]
@keljozap muchas gracias por tu explicación tan detallada. Tienes toda la razón frente a que la condición AND evalúa que ambas sean true o sino false. En la respuesta que di a ese parámetro es que NO devuelve True, devuelve "2 y 3" porque se cumplen ambas condiciones de que first name no es string y tampoco lo es last name (F y F = False)

En resumen se indica claramente la respuesta para la tabla que compates, menos una respuesta clara para el ultimo statement de la tabla 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/80206c21-62c2-442a-9c42-a4a9d2c408da)

**Comment by keljozap** [comment]
Hola @juliansernave ya creo saber cual es tu error. El ejercicio nunca indica que se debe devolver 2 y 3 al mismo tiempo, de hecho indica SI la variable 1 NO ES string retorne 2. SI la variable 2 NO ES string, retorne 3. El ejercicio nunca indica que deben tenerse en cuenta los demás casos, el control solo esta evaluando estas dos condiciones por separado.

Así si la entrada del control es None y True, la respuesta sería
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/c9cdf3d9-82c6-43b1-9a86-ea25c82eb6a6)

**Comment by keljozap** [comment]
Hola @juliansernave, no tiene relevancia para el ejercicio plantear el caso que indicas, no es necesario si el ejercicio no lo pide y en este caso no lo está indicando. Este ejercicio esta evaluando condicionales simples, es decir IF IF no condicionales compuestos es decir, IF ELSE que es donde cabria tu situación.

**Comment by juliansernave** [comment]
De verdad que yo entiendo lo que planteas, muchas gracias @keljozap, sin embargo no estoy de acuerdo. 

Agradezco que @luisvasv-teck revise el caso, y pues se cierre el issue si es el caso

**Comment by luisvasv-teck** [comment]
@juliansernave  cuál es tu email para validar tu código?

**Comment by juliansernave** [comment]
Hola @luisvasv-teck, claro que sí

jsern@softserveinc.com

**Comment by luisvasv-teck** [comment]
@juliansernave creo que ya todo ha sido ampliamente respondido por los compañeros, pero revisando tu lógica y el enunciado, realmente el ejercicio no está bien del todo, tomando esta info del notebook que resolviste:

<img width="971" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108821097/173a99bf-ebb7-4ec2-87ba-e8d9653b4941">

si miras efectivamente te está indicando que retornes el número de lo que no cumplió y en tu lógica estás retornando un `str` 
<img width="221" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108821097/b6744f18-0f95-4f6a-9912-66e7dbed2555">

y validando la lógica de la ejecución de los parámetros que te fallan, este es tu resultado:
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108821097/027f58ed-feb1-4f71-b472-5b2b3c877921)

Porfa recuerda tener en cuenta las constraints de los ejercicios, ya que está pidiendo que retorne `bool` o `int` dependiendo de caso. Pero en ninguna parte del enunciado `str`

**Comment by juliansernave** [comment]
Muchas gracias @luisvasv-teck por tu respuesta
