### ISSUE TITLE
NO SE PUEDE RESOLVER- Punto 10 condicionales 

### ISSUE THREAD

**Issue by juliansernave** [codingupmyfuture/bootcamplinuxpython#112]
Cordial saludo @luisvasv-teck  @luisvasvv 

El tercer escenario del punto 10 no fue evaluado satisfactoriamente sin embargo, cuando lo evalúo obtengo la respuesta del bot:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/b31d8f35-e827-46c4-a1db-38e9d4d85d43)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/bae16092-6687-4969-a636-d6d3e94b4f9e)

Quedo atento, muchas gracias!

**Comment by Josjisut** [comment]
Debes revisar el escenario de "param_01 = (4,), param_02()" pues es que te esta generando el error.
Tambien para que te sea mas facil verificar por que se genero el fallo en la parte del inicio del documento hay una tabla que te muestra el error que se genero, para que sea mas facil encontrarla te comparto un error que se me genero a mi y lo encontre en esta tabla. 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/113815029/648941b5-9928-4841-ae31-00e214b60e80)

**Comment by juliansernave** [comment]
Gracias @Josjisut ! es correcto, el error es mío porque me faltó una condición
