### ISSUE TITLE
Error ejercicio #5, taller #5 [Funciones]

### ISSUE THREAD

**Issue by melenabelt** [codingupmyfuture/bootcamplinuxpython#117]
Buenas tardes.

He probado de múltiples formas la manera de resolver el punto 5 del taller de Funciones y el bot sigue calificando mal el punto a pesar de que el resultado es el mismo.

<img width="590" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/5cdd5f23-cb56-487b-a2ac-748af56a28b1">

---
[Evidencia impresión] - Un solo parámetro para no llenar demasiado este issue
Respuesta estudiante

<img width="674" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/8d60286e-013a-41e0-b4dd-5e8f4b32af02">

Respuesta bot

<img width="678" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/766ecbfc-5e3d-4c52-a5c1-75b430474c85">

De igual forma las impresiones de los árboles están iguales como se pudo observar en los screenshots anteriores

Quedo atenta. Gracias.

**Comment by Elioric** [comment]
Buenas tardes, @melenabelt

Estoy de acuerdo y tengo la misma duda. También he enviado varias veces ese ejercicio y aunque visualmente es la misma respuesta, el bot no la reconoce como correcta. En el PDF tampoco se alcanza a visualizar la calificación debido al tamaño de la impresión, por lo cual sólo se puede validar con lo que sale en la primera página

**Comment by edcalderin** [comment]
Noten que en la respuesta del bot, hay un espacio adicional en última rama.
\n---------\n  Bot: \n--------- \n

Solo hay que calibrar bien el código para poder superarlo.

**Comment by Elioric** [comment]
Buenas tardes, @melenabelt

Estoy de acuerdo y tengo la misma duda. También he enviado varias veces ese ejercicio y aunque visualmente es la misma respuesta, el bot no la reconoce como correcta. En el PDF tampoco se alcanza a visualizar la calificación debido al tamaño de la impresión, por lo cual sólo se puede validar con lo que sale en la primera página

**Comment by Elioric** [comment]
@edcalderin, la respuesta en mi caso es exactamente la misma que devuelve el bot y sigue apareciendo como incorrecta.

![Screenshot_2023-09-30-15-02-35-474_cn.wps.moffice_eng.jpg](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/4d10468e-464f-4c9f-81eb-24795b2ebbb0)

**Comment by melenabelt** [comment]
Tampoco veo la diferencia con mi respuesta. Está igual.

**Comment by edcalderin** [comment]
@Elioric en el notebook ```LVL2.07.format.ipynb```, el código de la celda bajo el titulo "FORMAT AVANZADO 1", me sirvió como referencia para ese punto. Ojalá tambien te pueda servir de ayuda!

**Comment by Elioric** [comment]
> @Elioric en el notebook `LVL2.07.format.ipynb`, el código de la celda bajo el titulo "FORMAT AVANZADO 1", me sirvió como referencia para ese punto. Ojalá también te pueda servir de ayuda!

Muchas gracias, @edcalderin, no sé exactamente cuál es la diferencia pero ya lo calificó correctamente. Quizá porque el `print` no lo esperaba por partes sino del árbol ya completado. Ya con eso solucioné.

**Comment by JoseJulianMosqueraFuli** [comment]
<img width="590" alt="1" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/9a0e23bf-a4c1-4085-b93c-cb11047e47b3">

La principal diferencia está en los espacios ' ' un espacio al final como lo dijio anteriormente edcalderin, tienen que tener cuidado con eso, a pesar de que se imprima identico si los espacios no cumplen, no es valido para el bot. :)

**Comment by Elioric** [comment]
> <img alt="1" width="590" src="https://user-images.githubusercontent.com/56327269/271797463-9a0e23bf-a4c1-4085-b93c-cb11047e47b3.png">
> La principal diferencia está en los espacios ' ' un espacio al final como lo dijio anteriormente edcalderin, tienen que tener cuidado con eso, a pesar de que se imprima identico si los espacios no cumplen, no es valido para el bot. :)

@JoseJulianMosqueraFuli en la respuesta que había pasado anteriormente, se puede validar que la cantidad de espacios, guiones y saltos de línea es la misma, por lo tanto no era por ese lado. Tiene más que ver con la forma en que se está formateando el texto cuando se devuelve, que puede tener más o menos espacios, aunque el bot lo represente con un sólo espacio (puede ser por el formato del documento de reporte de resultado)

**Comment by luisvasv-teck** [comment]
Considero que no se deben enredar con espacios o cosas complicadas, deben entender que hay funciones que centran las cosas como` str.center ` o` {:{size}}`.

Para dibujar el cuadro debe tener una longitud fija y después centrar los textos dependiendo de la iteración
