### ISSUE TITLE
Error - entrega inválida taller 3

### ISSUE THREAD

**Issue by JDCARDONA18** [codingupmyfuture/bootcamplinuxpython#118]
Hola podrías por favor ayudarme con este error? Dice entrega invalida, no modifiqué el nombre ni la estructura...

![IMG-20231001-WA0013.jpg](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/140763699/17bea5cb-e8a9-4e74-9ddf-1c439abbb326)

**Comment by jose-92** [comment]
Hola JD la unica solucion que pude encontrar para ese problema fue modificar el ejercicio 5 ..... exactamente la validacion que se hace para saber si los parametros no son None ...espero que te puedas guiar ....
