### ISSUE TITLE
Duda calificación punto 8 Taller Bucles Nivel 2

### ISSUE THREAD

**Issue by lauris9449** [codingupmyfuture/bootcamplinuxpython#119]
Buenos días 

En el punto 8 del taller de bucles 

(Escribir dentro del cuerpo de la función function la lógica que permita borrar las keys **que contengan un valor** en específico de un diccionario dado y luego de esto, imprima y retorne el diccionario resultante.

Si el valor no existe en el diccionario se retornará el diccionario sin ningun cambio.
Se deben borrar todas las **keys que contengan el valor especificado**.
Nota: El diccionario será dado como parámetro de la función al igual que el valor que debe buscar. Usted debe retornar el diccionario sin cambios si no encuentra el valor o el diccionario sin el valor especificado.)

function({'track': "Low",  'ids': [1, "C", 3]}, "C")

En este caso me genera duda por qué se retorna la llave ids si dentro de sus valores está el valor C, por lo tanto, se debería borrar esta llave.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/127144786/65c326bf-ede3-4bac-b635-4aa845500937)

**Comment by keljozap** [comment]
Hola @lauris9449 ese valor se retorna ya que el ejercicio está pidiendo borrar las keys que contengan ese valor, y en el caso de esa key contiene una lista que a su vez contiene ese valor y no solo la letra C.

Espero haberte dado claridad.

Saludos!.
