### ISSUE TITLE
Duda calificación taller 1, puntos 1 al 5

### ISSUE THREAD

**Issue by manferjam0508** [codingupmyfuture/bootcamplinuxpython#120]
Buenos días:
. 
El motivo del presente mensaje es para confirmar una situación ocurrida con el taller 1: en el primer intento saqué 2.5 . Realicé la respectiva corrección de los puntos que me quedaron mal (fueron los 5 primeros puntos), se hizo la corrección según lo indicado en el bot; pero al momento de enviar la corrección, me sale la calificación igual de 2.5, como si no me tomara la corrección realizada, ademas de haber hecho las pruebas de ejecución cambiando el valor de los parámetros, me toma como si mi respuesta sigue siendo NONE; adjunto los pantallazos para solicitar cordialmente de su colaboración, estaré atento ante cualquier novedad, de antemano muchas gracias.

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/b60dc012-d990-4fff-b70b-5f591fb995f7)

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/f9e70436-87a1-4c05-8a59-cc002bf77141)

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/0773fd12-432a-4544-acb1-eb720c1f26ee)

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/ebe970dd-7888-402c-91f0-4698085b9f13)

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/61146112-e187-408d-b4a5-cf1407c921f3)

**Comment by MeliDevClicky** [comment]
@manferjam0508 Hola, parece que en tu implementación estás asignando el resultado de un print a tu variable resultado_comparacion. En lugar de eso, deberías asignar un valor booleano a resultado_comparacion: True si se cumple la condición que estás comparando y False en caso contrario. Después de asignar el valor, puedes usar print para mostrar el resultado. Si no lo haces de esta manera, el valor de resultado_comparacion siempre será None, ya que print no devuelve ningún valor, y por ende, el bot no podrá realizar la validación correctamente.

Aquí tienes un ejemplo de cómo podrías estructurarlo:

resultado_comparacion = <tu_condición>  # True o False dependiendo de si se cumple la condición
print(resultado_comparacion)

**Comment by manferjam0508** [comment]
> @manferjam0508 Hola, parece que en tu implementación estás asignando el resultado de un print a tu variable resultado_comparacion. En lugar de eso, deberías asignar un valor booleano a resultado_comparacion: True si se cumple la condición que estás comparando y False en caso contrario. Después de asignar el valor, puedes usar print para mostrar el resultado. Si no lo haces de esta manera, el valor de resultado_comparacion siempre será None, ya que print no devuelve ningún valor, y por ende, el bot no podrá realizar la validación correctamente.
> 
> Aquí tienes un ejemplo de cómo podrías estructurarlo:
> 
> ```
> resultado_comparacion = <tu_condición>  # True o False dependiendo de si se cumple la condición
> print(resultado_comparacion)
> ```

Por eso, ya hice la corrección del resultado de la comparación me arroje al tipo booleano; solo que en el momento de subir la corrección de los puntos, parece que el bot no tomó las correcciones realizadas y eso que antes hice el cambio de los parámetros para probar, que funcione cuando sea falso o cuando sea verdadero; todas esas pruebas las hice sino que el bot no reconoció los cambios que hice y guardé, a eso me refiero

**Comment by MeliDevClicky** [comment]
@MeliDevClicky  

> > @manferjam0508 Hola, parece que en tu implementación estás asignando el resultado de un print a tu variable resultado_comparacion. En lugar de eso, deberías asignar un valor booleano a resultado_comparacion: True si se cumple la condición que estás comparando y False en caso contrario. Después de asignar el valor, puedes usar print para mostrar el resultado. Si no lo haces de esta manera, el valor de resultado_comparacion siempre será None, ya que print no devuelve ningún valor, y por ende, el bot no podrá realizar la validación correctamente.
> > Aquí tienes un ejemplo de cómo podrías estructurarlo:
> > ```
> > resultado_comparacion = <tu_condición>  # True o False dependiendo de si se cumple la condición
> > print(resultado_comparacion)
> > ```
> 
> Por eso, ya hice la corrección del resultado de la comparación me arroje al tipo booleano; solo que en el momento de subir la corrección de los puntos, parece que el bot no tomó las correcciones realizadas y eso que antes hice el cambio de los parámetros para probar, que funcione cuando sea falso o cuando sea verdadero; todas esas pruebas las hice sino que el bot no reconoció los cambios que hice y guardé, a eso me refiero

@manferjam0508 Hola, estás asignando a resultado_comparacion el valor que retorna la función print, que es None. En lugar de hacer `resultado_comparacion = print(True)`, deberías directamente asignar el valor booleano con `resultado_comparacion = True`. De esta forma, la variable contendrá el valor booleano que esperas y no el resultado de la función print.

**Comment by manferjam0508** [comment]
@MeliDevClicky te hallo la razón, el error era por que tenía el print y aunque en la evaluación funcionaba igual, en el momento de las pruebas el bot lo tomaba como none, muchas gracias

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/cb85b57e-486a-433f-b6fe-6e7cde9cc5fc)
