### ISSUE TITLE
Taller Condicionales punto 1 

### ISSUE THREAD

**Issue by hrriverar** [codingupmyfuture/bootcamplinuxpython#121]
Hola me pueden decir, por favor, que es lo que tengo mal en este codigo. No entiendo donde tengo el problema, debería retornarme None pero no me lo retorna, entonce el bot dice fallo en la ejecucion. EL bot me dice esto, pero no los entiendo.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/134157669/fc7df467-6960-4976-a1a1-245657a8481a)

**Comment by JoseJulianMosqueraFuli** [comment]
Hola, @hrriverar, la restricción de que no reciba None, no la tienes, como el bot creo que ejecuta esta primero no puede ejecutarlo.
*Nota*: desde hace rato nos prohibieron subir código, puedes subir de evidencia las correcciones del bot y especificar el punto.
