### ISSUE TITLE
Funciones Punto 1.

### ISSUE THREAD

**Issue by hrriverar** [codingupmyfuture/bootcamplinuxpython#122]
Hola buenas, me pueden decir que es lo que tengo mal, veo que las respuestas son las mismas que la maquina pero no veo cual es mi fallo. Me califica como cero.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/134157669/ec9d39d2-3be8-425c-b201-a26ec3806fe9)

**Comment by JoseJulianMosqueraFuli** [comment]
Hola @hrriverar , no son las mismas, porque las llaves tienen unos asteriscos adicionales (*) los resultados parecen estar correctos, elimina los asteriscos e intenta.
```python
{'**suma**': } != {'suma':}
```

**Comment by hrriverar** [comment]
Hola Julian gracias por la respuesta. Mira los asteriscos los tengo como parte del string, osea "**suma**" como dice el taller que deben ser,  pues, tenía entendido que no afectaria dado que solo es el nombre de la llave.

**Comment by JoseJulianMosqueraFuli** [comment]
Intenta como te indiquen eliminando los asteriscos.
Nos cuentas por aquí. 😁

**Comment by luisvasv-teck** [comment]
el tema es que copiaste el markdown y por eso te sale así

en markdown la negrilla es: `**pares**` y se vería algo cómo así: **pares**

<img width="214" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108821097/fa2ae43d-45c7-4638-9c58-9e66a664f8d0">
