### ISSUE TITLE
Duda respuesta bot | ejercicio # 4 , taller #6 [Archivos simples]

### ISSUE THREAD

**Issue by melenabelt** [codingupmyfuture/bootcamplinuxpython#124]
Hola!

Estoy recibiendo este mensaje en el ejercicio # 4 del taller # 6

<img width="535" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/af13e38e-91d2-4914-8052-b90b4993970a">

Estuve investigando de qué se trataba y el código como tal es muy sencillo y no encuentro relación con este problema.

Agradecería mucho una ayuda o guía para saber en qué consiste

❤

**Comment by andresarad1** [comment]
x2

**Comment by Elioric** [comment]
X3

**Comment by JoseJulianMosqueraFuli** [comment]
x4 😢

**Comment by melenabelt** [comment]
> x4 😢 El bot evalua el return de la segunda linea, aunque nos pide la primera, solo la imprime.

Pero es que, que al menos recibiera el return, pero nadimbi 😖

**Comment by edcalderin** [comment]
mismo headache! lo solucioné al imprimir y retornar el readline(), sin almacenarlo en una variable para luego retornarla. Parece que ese enunciado no fué muy claro.

**Comment by Elioric** [comment]
> mismo headache! lo solucioné al imprimir y retornar el readline(), sin almacenarlo en una variable para luego retornarla. Parece que ese enunciado no fué muy claro.

Entonces, según eso, el readline() estaría leyendo dos líneas en vez de solamente la primera?

**Comment by melenabelt** [comment]
Es que, en ese orden de ideas pareciese que el bot está mandando la función 2 veces. En la primera recibe la primera línea y en la segunda, la segunda por hacerlo con readline()

**Comment by edcalderin** [comment]
Actua como un puntero, va devolviendo el siguiente elemento en un iterador, en el primero llamado devuelve la primera linea (lo que se "printea"), en el segundo llamado la segunda linea (lo que se retorna).

**Comment by melenabelt** [comment]
Por qué lo hace como un iterador si se supone que la función solo se debe llamar una vez?

**Comment by edcalderin** [comment]
@melenabelt deberia ser solo una vez, pero veo que readline() lo ejecuta dos veces dentro de la funcion.

**Comment by melenabelt** [comment]
@edcalderin sí, eso pensé. Gracias por tu respuesta btw 🥰

**Comment by lrestrepoteck** [comment]
Hola Pero yo lo estoy ejecutando y si guardo la primera ejecucion en una variable despues la debuelvo con el return la variable entonces no entiendo como es que se ejecute dos veces readline(). si me pueden ayudar por favor.

**Comment by lrestrepoteck** [comment]
lo que yo tengo es algo asi:
with open(path, "r") as archivo:
     linea= archivo.readline()
     print(linea)

     return linea

**Comment by melenabelt** [comment]
@lrestrepoteck no mandes código por fi’. 🥹

**Comment by lrestrepoteck** [comment]
ok

**Comment by melenabelt** [comment]
¿Te genera el mismo error?

**Comment by ChristYela** [comment]
Me pasa eso mismo
