### ISSUE TITLE
Validar respuesta punto 4 - Taller condicionales 

### ISSUE THREAD

**Issue by tatianaochoab** [codingupmyfuture/bootcamplinuxpython#125]
En el ejercicio se indica que se debe "verificar que los catetos sean números **enteros (int)** ó números de punto **flotante (float)**". Sin embargo, segun la respuesta entregada por el bot se está empleando un tipo de dato **numpy.float64**, el cual según entiendo corresponde a una librería externa. 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63075298/309f9eae-8ac2-454e-8e74-d80d4429e797)
Al enviar los parámetros con ese tipo de dato en la ejecución no se pueden validar los escenarios donde la suma de los cuadrados de los catetos es mayor a 0, dado que no pasa el filtro de los tipos de datos.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63075298/639b493b-eae2-43e7-b7f8-79751fbb979d)
Cuando se ejecuta el codigo en mi local la respuesta es la esperada por el control
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63075298/abb20162-4628-4da2-a7c6-2b4031e30aa1)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63075298/6cfd8f18-3118-4725-bf0b-a176d43a7364)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63075298/f8147ffe-bbbe-457b-8636-12a1740367a5)

**Comment by jonathanlantiasas** [comment]
Tengo el mismo problema que la compañera @tatianaochoab, hago las validaciones si los datos son o enteros o flotantes con las siguientes comparaciones:
`(type(cateto_1) == int or type(cateto_1) == float) and (type(cateto_2) == int or type(cateto_2) == float)`

al realizar la prueba con los valores `function(0.5, 7)`el bot arroja que la respuesta a la salida de mi solución es `0` para todos los casos. Probé y para este caso la respuesta debería ser `49.25` pero el bot lo califica en `0`.

**Comment by tatianaochoab** [comment]
[keljozap](https://github.com/keljozap) 
En un principio estaba validando tal cual el compañero [jonathanlantiasas](https://github.com/jonathanlantiasas) es decir si los catetos eran un tipo de dato int o float se ejecutaran las acciones requeridas. 

Sin embargo al darme cuenta de que se envia un tipo de dato distinto cambien la condición a:

- Si los catetos son distintos a tipos de datos string, diccionario, tupla, etc... se ejecutaran las acciones, de esta manera logré dar solución al problema. Aunque considero que no era lo más optimo

**Comment by keljozap** [comment]
Hola chicos, en el curso vimos un método que verifica que si un "objeto" es algo o no es algo, que no es type, creo que ahí radica el error, ya que type retorna el tipo del objeto Ó puede retornar un objeto completamente nuevo, mientras que con el  método que les indico, se verifica si el objeto es _____ o es una subclase de ______.

Espero puedan llenar los espacios.

Cualquier cosa me cuentan.
