### ISSUE TITLE
Duda de Ejercicio 8 del taller de funciones

### ISSUE THREAD

**Issue by Cris-Cod** [codingupmyfuture/bootcamplinuxpython#126]
Hola

En el ejercicio 8 en la parte de 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/75702892/a82c6377-400e-43e1-ac20-6b39d3f27e27)

En la parte de estandarizar el texto yo entiendo de ordenar alfabéticamente las letras únicas ingresadas del Sting, pero al revisar la respuesta del Bot me muestra esta respuesta 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/75702892/dbd1f7b8-a2c8-4c7e-ac98-a16cb86d709e)

y al ordenar las letras únicas, mi es resultado es:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/75702892/1a3ec491-4f83-4d1d-8c79-80557fc64c08)

que otra estandarización se debería realizar?

**Comment by davidlopez-190** [comment]
X2

**Comment by marya277** [comment]
El objetivo de la función unique_values es tomar un texto de entrada y devolver las letras únicas en ese texto después de estandarizarlo. La estandarización en este contexto generalmente significa convertir todas las letras a minúsculas y luego ordenarlas alfabéticamente. Tambien mirar esa parte que no hayan letras duplicadas, que cada letra aparezca una sola vez.

**Comment by davidlopez-190** [comment]
@marya277 gracias por la respuesta,  en mi caso la respuesta que obtengo para la entrada : 'CodingUpMyFuture'   es  'cdefgimnoprtuy'   donde estoy realizando:
1) dejarlo en minisculas, 
2) borrar duplicados 
3) hacerle un sort .. 
pero la respuesta del bot entrega otro orden con las mismas letras : 'otruimfpedgnyc'  
no se como darle ese orden que genera el bot

**Comment by marya277** [comment]
Al ordenar los caracteres únicos antes de unirlos a la lista, garantizas que obtendrás el mismo orden alfabético específico que muestra el bot en su respuesta.

**Comment by luisvasv-teck** [comment]
Dentro de la función `function` debe crear una función llamada  `unique_values` en esta función si se envía `aaabbbb`, debe retornar `ab` y dicha función siempre será la primera en ser ejecutada.

**Comment by luisvasv-teck** [comment]
> Hola
> 
> En el ejercicio 8 en la parte de
> 
> ![image](https://user-images.githubusercontent.com/75702892/272451428-a82c6377-400e-43e1-ac20-6b39d3f27e27.png)
> 
> En la parte de estandarizar el texto yo entiendo de ordenar alfabéticamente las letras únicas ingresadas del Sting, pero al revisar la respuesta del Bot me muestra esta respuesta
> 
> ![image](https://user-images.githubusercontent.com/75702892/272451677-dbd1f7b8-a2c8-4c7e-ac98-a16cb86d709e.png)
> 
> y al ordenar las letras únicas, mi es resultado es:
> 
> ![image](https://user-images.githubusercontent.com/75702892/272451807-1a3ec491-4f83-4d1d-8c79-80557fc64c08.png)
> 
> que otra estandarización se debería realizar?

Realmente no dice eso, en ninguna parte de la expresión se dice que sé tiene que ordenar
