### ISSUE TITLE
Duda respuesta bot | ejercicio # 3 , taller #7 [Archivos JSON]

### ISSUE THREAD

**Issue by melenabelt** [codingupmyfuture/bootcamplinuxpython#127]
Hola!

Estoy recibiendo los siguientes mensajes en el ejercicio # 3 del taller # 7

1. Al hacerlo sin incluir el objeto en una lista (posteriormente lo incluí en la lista por como está devolviendo la respuesta el bot)

<img width="526" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/65eadf18-8edc-41bf-86e3-eb58398efce1">

<img width="565" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/6888a898-89d2-4547-b607-98edb5c70247">

2. Incluyendo el objeto en una lista

<img width="533" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/d0f28a85-0f4c-480b-b0ed-af4ffd9ce3ff">

<img width="562" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/49c4f61c-1fe2-4372-9a7f-99a7e2fef4e3">

Al ejecutar mi código en otros entornos funciona perfectamente, también funciona bien en el Collab cuando ejecuto la función para testear la misma.

Alguna idea?

Mil gracias

**Comment by andresarad1** [comment]
x2

**Comment by JoseJulianMosqueraFuli** [comment]
x3
he podido retornar bien la ruta, pero al escribirlo me falta un detalle. 😭

**Comment by Elioric** [comment]
x4 jaja

**Comment by lrestrepoteck** [comment]
Hola el mio funciona pero no se de donde saca un monton de listas en la solucion del problema.
es como si la solucion quedara dentro de otra lista pero no se por que?

**Comment by melenabelt** [comment]
En qué sentido te funciona? Te lo califica correctamente? O te pasa lo que me pasaba a mi en los primeros 2 screenshots?

**Comment by lrestrepoteck** [comment]
no me lo pone en 0 pero la ejecucion funciona solo que no me sale el resultado dentro de unos [] adicionales que exige la respuesta.

**Comment by JoseJulianMosqueraFuli** [comment]
Entonces es como el primer caso que presentó @melenabelt , y no funciona. 🥺

**Comment by lrestrepoteck** [comment]
<img width="1201" alt="Screenshot 2023-10-04 at 6 41 20 PM" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108086723/ed5ea583-40af-414f-b947-16b3ddb1b4f3">
<img width="1201" alt="Screenshot 2023-10-04 at 6 42 36 PM" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108086723/856ea5b2-da36-4689-bb7d-07f9eb910c8e">

**Comment by lrestrepoteck** [comment]
estos son los resultados que obtengo pero como ven mi respuesta no coincide con la de control por unos [] adicionales.

**Comment by JoseJulianMosqueraFuli** [comment]
@luisvasv-teck , ¿Nos podría dar una mano(guía o explicación)? Lo he intentado de varias maneras e intenté recrear el typerror, aún así no encuentro la solución.

De antemano gracias.

**Comment by ChristYela** [comment]
Apenas en darle caña a este taller de JSON con Python.

**Comment by melenabelt** [comment]
@lrestrepoteck efectivamente, es lo mismo que me pasó la primera vez que lo envié.

**Comment by ChristYela** [comment]
Igualmente y también pasa con los ejercicios de  archivos

**Comment by keljozap** [comment]
Hola chic@s, este parece ser un error del notebook, si aprecian bien, uno de los diccionarios esta envuelto en una capa adicional y esto al no ser igual en el otro objeto hace que falle la comparación. Estaremos revisando el notebook (Seguimos trabajando para su satisfacción). Apenas tengamos el arreglo les comentamos.

**Comment by lucasrestrepo** [comment]
Gracias

**Comment by keljozap** [comment]
Hola chicos ya pueden probar de nuevo con el notebook de JSON, ya fue corregido.

**Comment by melenabelt** [comment]
Efectivamente, ya está funcionando. Gracias!

**Comment by lrestrepoteck** [comment]
Que buenos ya estamos bien.

Muchas Gracias.

**Comment by ChristYela** [comment]
Gracias a todos por sus respuestas
