### ISSUE TITLE
taller # 7[ TALLER ARCHIVOS] Duda respuesta del bot *FileNotFoundError: [Errno 2] No such file or directory  

### ISSUE THREAD

**Issue by davidlopez-190** [codingupmyfuture/bootcamplinuxpython#128]
Hola
Estoy recibiendo en siguiente mensaje en todos los ejercicios del taller donde solicita leer un archivo
 
: El ejercicio ha fallado debido a: **Traceback (most recent call last): * File "/Users/lvasq/repositories/personal/evaluator/evaluator/src/qualifier/exercise.py", line 236, in _run_exercise * exec(self._handle_code(code), globals(), objs) * File "", line 15, in * File "", line 4, in function *FileNotFoundError: [Errno 2] No such file or directory: 'PYLVL2EFLS-01.txt'**

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/74997508/998f8a75-9a3f-405f-9a1f-edb2d05b2131)

En mi entorno de trabajo de Google colab funciona correctamente ,primero  cargo el archivo con el siguiente comando para hacer las pruebas

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/74997508/6a907887-835c-4837-8e30-2388e106a8e4)

En el código del primer ejercicio por ejemplo para leer el archivo lo hago de la siguiente manera:

`with open("PYLVL2EFLS-01.txt", "r") as archivo:`

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/74997508/907e546a-416b-4147-9da2-40a9474bf0b6)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/74997508/7c65cd55-2e3c-413d-8ba9-c6bd612d286d)

La función en el entorno de Google colab funciona normalmente, pero ya en el bot no funciona entiendo es que no puede encontrar el archivo en la ruta indicada en la línea 4
Alguna idea para solucionar este error ?

Muchas gracias

**Comment by lucasrestrepo** [comment]
Hola Muchas gracias @davidlopez-190 por crear este problema ya que yo me estoy enfrentando con exactamente lo mismo. entonces seria bueno en el taller que se definiera como el bot esta buscando los archivo y si estos estan ubicados en el mismo folder en el que corre el bot. Por que esto pienso que puede estar haciendo la diferencia y si alguien ya resolvio este problema que nos ayude para poder superar este taller.
De antemano muchas gracias si nos pueden apoyar.

**Comment by Elioric** [comment]
Buenos días,

Lo que ocurre es que estás dejando la ruta y nombre del archivo quemado por defecto. Debería quedar de la siguiente manera:

`
with open(path,"w") as archivo:
    ...
    ...
`

La ruta del archivo te la están pasando en la variable `path`. Por eso no se debe definir el nombre del archivo directamente en el comando.

**Comment by davidlopez-190** [comment]
@Elioric muchas gracias , con ese cambio en el with ya funciona

**Comment by lrestrepoteck** [comment]
Hola bueno esto esta bien pero entonces como hago el llamado a la funcion para que encuentre el archivo en el bot? no me queda clara esta parte

**Comment by davidlopez-190** [comment]
@lrestrepoteck  yo solo deje hasta la definición de la función en el notebook  .. borre el llamado de la función en el notebook porque me seguía generando el error en la calificación.
Entiendo que el bot hace el llamado de la función  y le pasa a la función la ruta donde el bot tiene los archivos.

**Comment by lucasrestrepo** [comment]
Muchas gracias David ya lo envie sin el llamado esperemos aver que pasa.
Muchas gracias por tu aclaracion.

**Comment by ChristYela** [comment]
No entiendo esa parte de la ruta (en teoría donde dice path, sería la ruta (nombre del archivo)

**Comment by ChristYela** [comment]
No entiendo nada de eso y en los issues no logro entender lo que tratan de explicar.

**Comment by Elioric** [comment]
Hola @ChristYela 

Cuál es tu duda exactamente?

**Comment by ChristYela** [comment]
No logro entender sobre poner el path. He puesto el path a secas y con la ruta/nombre d archivo. Y No me lo reconoce el bot. Así que no tengo la más remota idea de que más hacer.

**Comment by ChristYela** [comment]
@Elioric Ya me dieron respuesta en otro issue, y todo perfecto.
