### ISSUE TITLE
Duda respuesta del bot en el Taller Archivos

### ISSUE THREAD

**Issue by JenniGomez04** [codingupmyfuture/bootcamplinuxpython#129]
Buenas noches, ¿algún compañero que me pueda decir el porque del error?

Envié el trabajo de archivos y de todos los puntos solo ejecuto uno, de resto todos fallaron en la ejecución y comparo y la mayoría retornan lo que la respuesta de control: ejemplo de uno de los puntos:

![Retorno Bot](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/110871284/d0cd991a-c00e-4752-9cd4-1311a88bd98a)
![Esperado](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/110871284/6865e4cb-abd0-4e24-b6a1-1f634d2e7c19)

Quedo atenta, gracias!

**Comment by JoseJulianMosqueraFuli** [comment]
Este issue anterior te puede ayudar  https://github.com/codingupmyfuture/bootcamplinuxpython/issues/128

**Comment by keljozap** [comment]
Adicional, estas enviando un texto a la función y recuerdo que la función recibe es un path

**Comment by lucasrestrepo** [comment]
si solo es quitar los llamados a la funcion despues de hacer las pruebas locales.

**Comment by manferjam0508** [comment]
Buenas tardes, les confirmo que tengo mis dudas acerca del taller de archivos, y que el bot me arroja que no se pudo resolver y ha fallado en la ejecución, hice la consulta del issue anterior (el 128) en que involucra el import files, no se si añadiendo eso el bot me retorne nuevamente con todo el taller mal: ya que probé añadiendo la ruta del archivo del collab de mi cuenta, luego con la carpeta del profe (la ruta completa), después que borré el llamado de la función y después de 3 intentos; el bot me califica mal; adjuntaré los pantallazos para solicitarles cordialmente de su ayuda, gracias por su atención y estaré atento.

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/4e149adc-a73c-4a0c-888a-fbb33e0f170f)

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/ca7c6d43-1929-4b66-8ab1-2615a169456e)

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/004dd3b4-d0c9-4a45-a0c2-9e074816a9cc)

**Comment by JoseJulianMosqueraFuli** [comment]
Elimina la variable path que estas colocando al inicio de la función.

**Comment by ChristYela** [comment]
No entiendo nada de eso y en los issues no logro entender lo que tratan de explicar.

**Comment by manferjam0508** [comment]
@ChristYela a lo que me refería era que tenia valor en la variable path, los demás compañeros me recomendaban que dejara esa variable sola para que el bot ejecutara y podría trabajar; algo que si me funcionó en algunos puntos de los talleres de archivos y json.

**Comment by ChristYela** [comment]
No logro entender sobre poner el path. He puesto el path a secas y con la ruta/nombre d archivo. Y No me lo reconoce el bot. Así que no tengo la más remota idea de que más hacer.

**Comment by manferjam0508** [comment]
@ChristYela según me explicaron los compañeros con quienes resolvimos dudas el jueves pasado, como en la función incluyó a path como parámetro, me explicaron que hay que llamarlo como una variable sin un valor específico, debido a que en el bot ya tiene programado internamente el valor de path,  le mostraré un ejemplo de los que me corrieron:

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/8118ccbf-51c7-453d-b9b9-448b1690b42a)

En esta imagen definen la función con path como argumento, pero no se le pone el valor a path sino solo llamarlo, cuando usted lo ejecuta, no verá el resultado pero al enviarlo, el bot evalúa el comportamiento del path cargado y si se cumple o no con las condiciones del problema, yo también me sentía confundido, pero esa prueba se hace después de asegurarse que el desarrollo del problema le funcione correctamente de manera local; por que en ese entonces, tenía la ruta del archivo establecido dentro del path, pero al enviarlo para revisión, el path que maneja tiene una ruta diferente; espero que esta explicación sea de su comprensión.

**Comment by ChristYela** [comment]
@manferjam0508 Muchísimas gracias por sus explicaciones, Le agradezco por tomarse el tiempo y la cortesía de "explicarlo con plastilina". Muchos éxitos en las siguientes etapas de este Bootcamp.
