### ISSUE TITLE
Duda sobre el taller JSON punto 4

### ISSUE THREAD

**Issue by manferjam0508** [codingupmyfuture/bootcamplinuxpython#130]
Buenos días:

El motivo de este mensaje es acerca de una duda que tengo sobre el taller de JSON, puntualmente en el punto 4, donde dice que se debe leer el archivo PYLVL2FJSON-4.json y retornar el objeto resultante; ese archivo json se crea por código como en el anterior taller de archivos o se suministra dicho archivo por aparte?; si la respuesta es la segunda, no lo adjuntaron para realizar el ejercicio; no aparece y no sé como abordar este punto; para solicitar cordialmente de su colaboración, de antemano muchas gracias.

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/93574157-e790-4a44-a206-e2e11d4d229c)

**Comment by villarrealjk** [comment]
Hola @manferjam0508 

La respuesta es la segunda, el archivo adjunto está en el canal "trabajos" de Telegram.

Saludos!

**Comment by manferjam0508** [comment]
listo muchas gracias
