### ISSUE TITLE
Tengo problemas con los argumentos de prueba en el taller 5 de funciones

### ISSUE THREAD

**Issue by SS-Solar** [codingupmyfuture/bootcamplinuxpython#131]
En el taller 5 todos los ejercicios me dicen que no se puede resolver a pesar de que por lo menos en la primera primera prueba manual pasa el resultado, puede deberse a que no tengo bien configurados los parametros de entrada para que el bot evalúe con sus inputs,me podia mostrar como se debe hacer para que el bot haga esa prueba?
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/72994010/b2cfc97e-fdaa-479f-98ae-055f925144b2)
por ejemplo en la anterior imagen tengo lo que yo retorno de mi funcion, y la primera prueba la debe pasar, pero me dice directo que no se puede resolver.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/72994010/3d351e6a-49ed-4137-849d-46858ed6d2da)
En la anterior imagen tengo mi funcion y como le ingreso los parametros, pero no se por que dice que no se puede resolver

**Comment by CristianMongar** [comment]
Me pasa los mismo.

**Comment by JoseJulianMosqueraFuli** [comment]
Podrías agregar la tabla de resultados especificamente del punto 4 `PYLVL2GFUNC04` `Ejercicio no superado.Puntuación obtenida:...`
Y adicionalmente en  la ultima imagen contar_repeticiones(string, patter) te esta retornando el valor?

**Comment by SS-Solar** [comment]
El me retorna el valor en pantalla, y lo veo, y como se puede ver en la primera imagen, se ve que se ejecuta, pero cuando el bot me va a evaluar me dice no se puede resolver.
Por eso digo que si es posible que alguien que tenga el ejercicio completo, que me muestre solo la parte final

**Comment by SS-Solar** [comment]
Ya se que era, lo que pasaba para que el bot los tomara, era que la función que yo tenía por cada ejercicio tenía un nombre diferente.
Pero el bot solo tomo que las funciones se llamen function

**Comment by ChristYela** [comment]
@SS-Solar Al final si pudiste resolver su problema?
