### ISSUE TITLE
Entrega invalida

### ISSUE THREAD

**Issue by JDCARDONA18** [codingupmyfuture/bootcamplinuxpython#132]
Profe! Hice dos entregas el domingo, una a las 23.25 y la otra a las 23.52, me dice que estoy fuera de las fechas, tenía entendido que recibía calificación hasta las 23.59. Creo que a varios compañeros les pasó el mismo caso, ¿hay alguna forma que nos ayude con el tema?

**Comment by CrisGos** [comment]
Buenas noches, me pasó igual, realicé la entrega del último taller a las 11:32 PM y el bot respondió a las 12:06 AM informando que la entrega era inválida.

**Comment by anfereme23** [comment]
Hola profe @luisvasv-teck @luisvasvv confirmo que me paso la misma situación. Recibí respuesta del Bot hasta las 10;40 pm, después de eso envié un taller a las 11:27 pm y como no había respuesta lo reenvié a las 11:48 pm. El Bot solo volvió a funcionar pasada las 12:00 horas y retorno el mensaje de entrega invalida por la hora. 
![Captura de pantalla 2023-10-09 002718](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/20272366/f97574c4-1bb8-4dc7-8ba6-976e5d1ab81d)

**Comment by JayddCC** [comment]
Buenos días, tengo el mismo issue
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/95990829/54ee19ca-03e3-4a32-9da9-6a3602d33669)

Cabe resaltar que, aunque recibí los correos después de las 00:00, los envié antes de las 12
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/95990829/74dcf41a-57d7-4ac6-ae24-52f9dce3e749)

**Comment by ChristYela** [comment]
Buenas tardes, ya les dieron respuesta en el canal de Telegram, en avisos y notificaciones, y en calificaciones. Por favor revisen en Telegram para  más detalles.
