### ISSUE TITLE
Asistencia Bootcamp

### ISSUE THREAD

**Issue by lauratorres11** [codingupmyfuture/bootcamplinuxpython#15]
Buenas Tardes,

me registra una falta en el último archivo que envió el profesor hoy 14 de agosto 4pm, he asistido a todas las reuniones, me gustaría por favor si pueden validar el motivo del por qué me registra una falta.

Muchas Gracias.
Laura Torres Gaviria
Cel: 320 768 7824

**Comment by luisvasv-teck** [comment]
por favor escribir a : dliza@softserveinc.com
