### ISSUE TITLE
Trabajo final - columna para el hash en el csv

### ISSUE THREAD

**Issue by aquirozg** [codingupmyfuture/bootcamplinuxpython#152]
Hola chicos, tengo una duda respecto a la información de los json. Si bien se va a recopilar la información de los json en archvios csv, en la columna del hash sólo habrá valores de hash para las misiones que no son UNKN, pero para las misiones que sí son UNKN, el valor para esa misión en la columna del hash queda vacío o se llena con un identificador o ID aleatorio que no sea un hash?

Espero haber sido clara en la pregunta. Gracias!

**Comment by meligonzalezn** [comment]
Hola, en nuestro caso, como no se genera el hash, toma el valor de UNKNOWN

**Comment by aquirozg** [comment]
Listo, muchas gracias @meligonzalezn  !!
