### ISSUE TITLE
Falta String en el punto 2 del taller?

### ISSUE THREAD

**Issue by jhoannagil** [codingupmyfuture/bootcamplinuxpython#16]
Revisando el punto 2 veo que no se define un string para el ejercicio. 
<img width="1049" alt="Captura de Pantalla 2023-08-14 a la(s) 10 41 55 p m" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/41999290/ae74b4f6-37b9-4e8e-8ec3-b7d2e09c1656">

**Comment by JoseJulianMosqueraFuli** [comment]
En la parte de abajo cuando se llama a la función se define el string.

function(string)

**Comment by lrestrepoteck** [comment]
Me podrian explicar como llamo esa funcion para que me retorne el string en el codigo y como hacer para que aparesca return en la salida del codigo?

**Comment by JoseJulianMosqueraFuli** [comment]
# Claro, lo haré paso a paso.
## Cabe aclarar que las funciones se verán en posteriores entregas del curso.
### Explicación imagen anterior
La función la llamas o invocas como se llama esa función, para la imagen anterior ya está siendo llamada.

- **def function(mensaje):** <- Aquí el nombre de la función es function, con def defines que es una función en python, el mensaje es el parametro de entrada de esa función.

- **Nuestra tarea es crear lo que va dentro de la función** ""Escribe tu codigo"" <- aquí implementas la solución que tu consideras correspondiente, si deseas imprimir tu codigo dentro de la función bastará con un `print(<lo que quieras imprimir>)` y para retornar usar `return`.

- **function('Estoy aprendiendo')** <- Aquí estas llamando la función después de haberla creado o definido, con el mensaje 'Estoy aprendiendo.'

### Ejemplo
```
def soy_una_funcion(algunstring):
    algo = algunstring + "Prueba" # Cuerpo de la función aquí va tu codigo
    return algo  #Así puedes devolver un valor con return

#Despues de definida la función y que retorne algo.
soy_una_funcion('Hola soy una ') # Así invocas tu función
```
En este ejemplo:

1. Definiste la función soy_una_funcion que toma un argumento algunstringovalor.
2. Dentro de la función, concatenaste "Prueba" al argumento de entrada algunstringovalor.
3.Usaste return para devolver el resultado de la concatenación.
4.Luego llamaste a la función con 'Hola soy una ' como argumento y almacenaste el resultado en la variable resultado.
5. Finalmente, imprimiste el valor de resultado, que debería ser 'Hola soy una Prueba'.
Como estamos en colbar para probar, es dandole al runtime o el boton en el recuadro rojo.
![1](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/dc7af994-c5f2-4f99-a8e3-3ecf2c9d1b45)

Algo muy importante, es que python requiere una adecuada identación, tengan cuidado con eso en las funciones, en general son 4 espacios de identación, y considerar que el parametro de entrada es un string para este caso.

**Comment by Josjisut** [comment]
> Me podrian explicar como llamo esa funcion para que me retorne el string en el codigo y como hacer para que aparesca return en la salida del codigo?

Te recomiendo no modificar la estructura de la función pues en las reglas se aclara que no se permmite modificarla, únicamente mueve tu código y agrega tu respuesta en el "Return". Tu cómo tal no debes mover nada y la función tal como está es funcional solo debes correr el código
