### ISSUE TITLE
Duda con el punto 6 del taller #1

### ISSUE THREAD

**Issue by santiagocano298366** [codingupmyfuture/bootcamplinuxpython#17]
¡Hola a todos!

Me encuentro realizando el taller, haciendo punto 8 me queda una duda, con el apartado de retornar la posición de donde comienza la ultima palabra.
Mi duda es que no he logrado obtener la posición en la que está la ultima palabra usando solamente la función `.find()`, sin embargo, encontré en internet la función `.rfind()`, la cual me permite analizarlo desde el lado derecho del String.
Me gustaría saber si es válido realizarlo de esta manera, debido a que la función `.rfind` no la hemos visto con el docente @luisvasvv @luisvasv-teck .
Agradecería cualquier ayuda o alguna sugerencia para realizarlo de una manera mas eficiente.
Muchas gracias, estaré atento. 

```
text : str = "python softserve's bootcamp"
print("Posición de donde comienza la ultima palabra: ", (text.rfind('p')))
```

**Comment by JoseJulianMosqueraFuli** [comment]
¡Hola! En relación a la eficiencia, permítanme explicarles: En este escenario, el uso de `.rfind()` generalmente se considera más eficiente. Comparado con `.find()`, puede lograr el mismo objetivo, pero con menos pasos.

Por cierto, un pequeño consejo: asegúrese de revisar bien lo que se imprime en esta línea y cómo se relaciona con lo que se solicita en la instrucción:
```
print("Posición de donde comienza la última palabra: ", (text.rfind('p')))
```
@codingupmyfuture @luisvasv-teck, si en algo me equivoco, agradecería su corrección

**Comment by santiagocano298366** [comment]
> ¡Hola! En relación a la eficiencia, permítanme explicarles: En este escenario, el uso de `.rfind()` generalmente se considera más eficiente. Comparado con `.find()`, puede lograr el mismo objetivo, pero con menos pasos.
> 
> Por cierto, un pequeño consejo: asegúrese de revisar bien lo que se imprime en esta línea y cómo se relaciona con lo que se solicita en la instrucción:
> 
> ```
> print("Posición de donde comienza la última palabra: ", (text.rfind('p')))
> ```
> 
> @codingupmyfuture @luisvasv-teck, si en algo me equivoco, agradecería su corrección

¡Muchas Gracias Compañero!
Respecto a lo que dices de que revise la linea de código, tienes razón, no debería de ser 'b', cierto?, haciendo el cambio de esta manera:

`print("Posición de donde comienza la última palabra: ", (text.rfind('p')))`
Así esto me imprimiría el primera caracter desde el cual empieza la ultima palabra.
Agradezco si hay alguna otra corrección

**Comment by JoseJulianMosqueraFuli** [comment]
Si, para este caso sería lo ideal.
Como practica puedes intentarlo con el `.find()` si lo deseas, te doy una guía.
```
text= 'Cualquier texto aquí'
print("Ultima palabra del texto:", (text.find(<aquí tienes que llegar hasta la ultima parte,
 puedes hacerlo separando el string,
 y tomando el ultimo valor que separaste>)))
``` 
Son más pasos como te habia comentado, mientras con `.rfind()` lo estas recorriendo de final a inicio.
Depende de como abordes el problema. 😄 

Espero haberte sido de ayuda.

**Comment by santiagocano298366** [comment]
> Si, para este caso sería lo ideal.
> Como practica puedes intentarlo con el `.find()` si lo deseas, te doy una guía.
> ```
> text= 'Cualquier texto aquí'
> print("Ultima palabra del texto:", (text.find(<aquí tienes que llegar hasta la ultima parte,
>  puedes hacerlo separando el string,
>  y tomando el ultimo valor que separaste>)))
> ``` 
> Son más pasos como te habia comentado, mientras con `.rfind()` lo estas recorriendo de final a inicio.
> Depende de como abordes el problema. 😄 
> 
> Espero haberte sido de ayuda.

¡Muchas gracias por tu ayuda!

**Comment by Josjisut** [comment]
Hola, yo hice algo un poco diferente a las otras opciones, pues piden la posición de la última palabra entonces yo lo que hice fue, invertí el string y con find busque la posición del primer espacio (Que cómo estaba invertida sería el último espacio por ende el inicio de la última palabra de la frase) y a la longitud del string le quite ese valor

**Comment by alejandrazapatap** [comment]
[Josjisut](https://github.com/Josjisut) la verdad no lo pense de esa manera pero es un muy buen punto de vista, y seguramente de esa manera estaba pensando el profe tambien😊

**Comment by Josjisut** [comment]
También para que lo tengan en cuenta en algunos ejercicios se hace una multiprueba por así decirlo, esto quiere decir que el bot que califica cambia el string de entrada para comprobar que el algoritmo funciona como tal.
