### ISSUE TITLE
Novedad con al nota de la actividad

### ISSUE THREAD

**Issue by BetoHurtado** [codingupmyfuture/bootcamplinuxpython#19]
Buenos días.

Profesor, quería ver que tan viable es que podamos sacar unos minutos de la próxima clase para resolver dudas con respecto a la actividad en la parte de las entregas y resolución de actividades ya que al parecer no soy solo yo el que tiene dudas de como resolver los puntos, por ejemplo por mi parte la respuesta del correo es que tengo una nota de cero por que dice que los resultados no son correctos sin embargo al ver los puntos uso lo que piden y da la respuesta al ejecutar por ejemplo para el punto dos se pide: 
DESCRIPCIÓN: Tratamiento de String como cadenas de elementos.

Cuando se crea un objeto del tipo string en python, este es almacenado en pequeñas posiciones de memoria comenzando siempre con la posición cero, hasta el tamaño de la cadena de caracteres.

Para seleccionar un caracter específico colocamos el índice donde se ubica el caracter dentro de corchetes.

Ejercicio:
Dado el siguiente String, retornar el carácter en la posición 8

Mi código es: 

`return caracter

def function(mensaje):
    print (mensaje[8])
    return

function("Estoy aprendiendo")`

al ejecutar da correcto y retorna el carácter  que es: r

sin embargo me puntua 0.0 la verdad no entiendo segun esto entonces que debe dar y de esta forma tengo todos los puntos al ejecutar da la respuesta pero en todos los puntos me dice que me puntuo 0.0.

Quedo atento muchas, gracias.

**Comment by alejandrazapatap** [comment]
[BetoHurtado](https://github.com/BetoHurtado)pero según lo que tu enviaste:  
def function(mensaje):
print (mensaje[8])
return

function("Estoy aprendiendo")`

y lo que te estan pidiendo es que hagas un return. No se si me equivoco, pero ese es el error que yo veo😊

**Comment by BetoHurtado** [comment]
@alejandrazapatap como arias el return solo pondrías la variable y la posición? el tema va mas por ese lado al ser dentro de una función como se retorna. creo que la novedad esta hay ya que no hemos trabajado con funciones.

**Comment by alejandrazapatap** [comment]
[BetoHurtado](https://github.com/BetoHurtado)exactamente como tu lo dices:
 como arias el return solo pondrías la variable y la posición?
