### ISSUE TITLE
Posible error de calificación en el punto 8

### ISSUE THREAD

**Issue by Josjisut** [codingupmyfuture/bootcamplinuxpython#21]
Buenas,
Mi duda es por que el ejercicio nos pide (Adjunto el ejercicio):
Ejercicio:
Dado un input dado por el parametro string, escribir dentro de la función function la lógica que permita calcular, imprimir y retornar:
1. Colocar el primer caracter de cada palabra en mayuscula
2. cambiar el texto 'Curso' por 'Bootcamp'
3. cree una nueva variable que contenga el mismo string pero eliminando los espacios al inicio y final del string
Tener en cuenta que la longitud del string original len() es 30, la nueva variable con el string sin los espacios en blanco debe tener un len de 28.

Nos aclaran la longitud del 3rd string pero nos aclararan en el enunciado que se debe retornar en total 3 strings.

Ahora revisando la respuesta que se concidera correcta:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/113815029/595a7975-ff43-4f6f-a054-019104d63b8d)

La 3ra respuesta el espera un len(), de la longitud del string.

Alguno podría aclararme por favor si estoy entendiendo mal el enunciado o si se trata de un error del bot?.

**Comment by Andmontc** [comment]
Es correcto, la tercera respuesta se espera un len() del string sin los espacios en blanco, o sea con un strip.

**Comment by melenabelt** [comment]
Igual por aquí. El tercer punto me pide que elimine los espacios al inicio y al final, pero en ningún momento me dice que retorne len.

**Comment by Josjisut** [comment]
Si, el dia de ayer hablamos eso durante la sesión de preguntas y respuestas. Y se llego a la conclusión de que la 3rd respuesta si debe ser el len() de ese string.
Doy por cerrado el tema para evitar el spam y darle cabida a nuevos issues recuerden que igual pueden volver a verlo si revisan los temas cerrados.
