### ISSUE TITLE
Duda en ejercicio: PYLVL1ASTR-10

### ISSUE THREAD

**Issue by maurorpo** [codingupmyfuture/bootcamplinuxpython#22]
El punto 1 pide lo siguiente:

1. dado el string string1, separelo, acceda al ultimo elemento, reemplace su valor por python en mayusculas he imprimalo.

Que es lo que se debe de imprimir?

- Solo el dato valor cambiado?
-La lista con el valor cambiado?
-El string de nuevo, pero con el valor cambiado

**Comment by CristianMongar** [comment]
A lo largo los ejercicos se encuentran enunciados e instrucciones de ese tipo, es decir,  poco explicitas y abiertas a interpretacion. Y la verdad preocupa porque la forma en que desarrolles el ejercicio influirá en el la calificación.  O bueno... al menos es eso lo que tengo entendido, y puede que este equivocado, pero igualmente, creo que  para eso es este espacio.

**Comment by melenabelt** [comment]
Te refieres al ejercicio #10. Con este ejemplo comprendemos que estamos hablando del último elemento

**Ejemplo**:

 string = 'Hola mundo'
 Separar el string, acceder a su segundo elemento, convertir su primer caracter a mayuscula he invierta su sentido.

 string = string.split(' ')[1].title()[::-1]
 print(string) # -> imprime odnuM

**Comment by EstebanaOrozco** [comment]
Hola, estoy de acuerdo con que el enunciado no es claro. Yo devolví el string de nuevo, pero con el valor cambiado y recibí mala calificación. Toca devolver solo el valor cambiado.
