### ISSUE TITLE
Duda con ejercicio 2 de listas

### ISSUE THREAD

**Issue by melenabelt** [codingupmyfuture/bootcamplinuxpython#23]
<img width="647" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/fde33b07-e0d5-4649-a17a-3721f99db88d">

1. En el segundo cuarto de la lista me piden identificar el máximo y el mínimo, pero estos valores no se envían en el return y dado que es una máquina quien revisa los talleres, cuál es la idea del ejercicio como tal? Reemplazar todos los valores del segundo cuarto de la lista con el máx, min tipo:

segundo_cuarto = [max, min]

o es algo diferente?

2. En el tercer cuarto de lista, la idea es que quede algo como:

tercer cuarto = ['NN'] ?

Mil gracias ❤

**Comment by Josjisut** [comment]
Según yo lo entendí, piden que ese segundo cuarto sea reemplazo por un valor como el que tu tienes un arreglo de 2 valores [max,min], en cuanto a la parte de retornarlo el 5to punto pide concatenar todo en una lista saliente, ósea que al final quedaran los 4 cuartos modificados unidos en una sola lista.

**Comment by keljozap** [comment]
Hola @melenabelt para responder tu pregunta, la idea del ejercicio es calcular en una lista adicional cada literal pedido, es decir, para el punto 1 seria una lista resultante con la posición invertida de los elementos del primer cuarto, para el segundo literal seria una lista nueva con los valores maximo y minimo del segundo cuarto de la lista, y así sucesivamente.

Al final deberias tenes un return similar a algo como 

return lista1 + lista2 + lista3......


Espero haber resuelto tu duda, cualquier cosa, dejame saber.

Feliz dia!

**Comment by JonathanProf** [comment]
Buen día, veo un problema con el ejercicio debido a que cuando la lista se puede particionar con un número exacto por ejemplo 60, se tendrán 15 elementos por cada cuarto, pero cuando el número no es divisible exactamente entre 4, hay una confusión respecto del criterio, dado que por ejemplo si hay 50 elementos, aplicar la división daría 50/4=12.5 y no se define en el enunciado un criterio para aproximar hacia arriba o hacia abajo, ya que para este caso no se tendrán la misma cantidad de elementos por cada cuarto. Debido a esto veo que en la revisión realizada no hay consistencia con los casos de prueba. Gracias.

**Comment by davidlopez-190** [comment]
tengo la misma duda de @JonathanProf  cuando la division por 4 no dan un numero entero
