### ISSUE TITLE
Dudas con resultados de taller de booleanos

### ISSUE THREAD

**Issue by melenabelt** [codingupmyfuture/bootcamplinuxpython#24]
Todos los ejercicios pasaron y aún así, la nota recibida fue de 4.0; por tanto, si quisiera obtener un 5 no sabría cómo. Aquí van las evidencias:

- <img width="692" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/8785cd37-90e1-4d69-9c02-3b6c7bc872a8">

- <img width="701" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/2979fa06-ab0e-4704-a99c-ffad3d890ab0">

- <img width="694" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/983abc87-0976-4244-8c3b-2fc2f1cd9303">

- <img width="662" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/48d4ba7d-cc8d-4c85-8e80-af4699bbd97c">

- <img width="690" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/a30d5a6e-69dd-4caa-8c81-1e5851eb555e">

- <img width="680" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/70e371b2-b8a3-48b5-aa27-2874251ce1e5">

Muchas gracias 😁

**Comment by keljozap** [comment]
Hola @melenabelt  tienes toda la razón, quisieras enviar de nuevo el correo con tus ejercicios por favor? hemos modificado el calificador. en este caso, también se estaba evaluando la estructura de tu código y al igual que la respuesta correcta.

**Comment by melenabelt** [comment]
Claro que sí. Ya me pongo en esas, muchas gracias 🥰
