### ISSUE TITLE
NOMBRE DEL TALLER 3

### ISSUE THREAD

**Issue by JoseJulianMosqueraFuli** [codingupmyfuture/bootcamplinuxpython#26]
# Inquietud con respecto al taller 3

Hola saludo, alguien me podría explicar el porqué los archivos no coinciden.

Adjunto evidencia:
Archivo enviado por el canal de telegram:
![Captura de pantalla 2023-08-17 102341](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/a20fdf8b-9f90-46b9-b651-e9f58ee707d0)
Respuesta del correo
![Captura de pantalla 2023-08-17 102637](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/62502e5d-7ba7-4876-a702-3054508613bd)
Gracias 😄

**Comment by codingupmyfuture** [comment]
Hola @JoseJulianMosqueraFuli me puedes dar más detalle, que no vemos la diferencia que mencionas, para poder entender mejor tu pregunta

**Comment by codingupmyfuture** [comment]
Cuál es el email con que enviate?

**Comment by JoseJulianMosqueraFuli** [comment]
Este es el correo![Screenshot_2023-08-17-11-39-29-76_e307a3f9df9f380ebaf106e1dc980bb6.jpg](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/3c16ff39-1d76-4a57-b19b-be589421922d)

**Comment by codingupmyfuture** [comment]
tu email

**Comment by JoseJulianMosqueraFuli** [comment]
josejmosqueraf@unicauca.edu.co

**Comment by Josjisut** [comment]
Hola, @codingupmyfuture  También tengo el mismo problema, me marco error en el nombre del archivo.

**Comment by JoseJulianMosqueraFuli** [comment]
@codingupmyfuture  Aun se mantiene este error, aquí issues relacionados de compañeros:

- https://github.com/codingupmyfuture/bootcamplinuxpython/issues/36
- https://github.com/codingupmyfuture/bootcamplinuxpython/issues/35

**Comment by luisvasv-teck** [comment]
@JoseJulianMosqueraFuli el issue fue resuelto, ya les debió llegar calificación
