### ISSUE TITLE
Problema con la entrega del primer taller

### ISSUE THREAD

**Issue by CrisGos** [codingupmyfuture/bootcamplinuxpython#27]
Hola, tengo incovenientes con la entrega del primer taller, lo envié y me retornaron un correo con la siguiente información:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141366914/960513a6-8bcf-417b-883d-10473c4a9b9a)

Ya revisé el archivo y no hay ninguna modificación en el nombre,

**Comment by JoseJulianMosqueraFuli** [comment]
Me paso igual.
@codingupmyfuture, ¿nos pueden brindar soporte?

**Comment by keljozap** [comment]
Hola @CrisGos  y @JoseJulianMosqueraFuli por favor, envíen nuevamente el archivo al correo coding.up.my.future@gmail.com sin cambiar el nombre del archivo ni alterar la estructura de este. Una vez se corra de nuevo la calificación automática deberían obtener un correo con sus nota, si esto no ocurre, por favor vuelvan a copiarnos en este hilo.

Muchas gracias!
