### ISSUE TITLE
Problema con la respuesta de la pregunta 7 de la primer prueba

### ISSUE THREAD

**Issue by jaca131** [codingupmyfuture/bootcamplinuxpython#28]
estuve analizando la respuesta que el bot genera y la mía y el error que me muestra es que mi respuesta no esta en minúscula  pero analizando las dos respuestas están idénticas.

![Pregunta 7](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/127337474/f6f43206-e15d-41f7-89ad-097798db8c85)

**Comment by Elioric** [comment]
Buenas tardes, compañero.

Sí validas bien, en las entradas de control, verás que el resultado que arroja tu código es distinto al que devuelve el control. Especificamente en el que debe estar tipo título.

Tuyo =     "Bootcamp de python"
Control = "Bootcamp De Python"
