### ISSUE TITLE
Problema con envió de taller 

### ISSUE THREAD

**Issue by SS-Solar** [codingupmyfuture/bootcamplinuxpython#29]
Buenos dias, antes de ayer envié el primer taller pero hoy me llego respuesta de que mi correo no esta habilitado para realizar entregas.
Mi correo es jhoansgonzalez@outlook.com.
Mi teléfono es 3183342613.
los trabajos los he enviado a coding.up.my.future@gmail.com

![rebote](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/72994010/a514765f-484f-4c0f-b1b4-8429c278e7c9).

Entrando en otros errores, queria verificar por qué tengo una falta en asistencia de la cuarta clase, yo he entrado a todas las clases desde la misma versión de zoom y desde mis mismos 2 dispositivos (Android y PC).}

![asistencia](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/72994010/c15dc95c-b3c2-4b51-85ba-c8d0631dbf81)

**Comment by keljozap** [comment]
Hola @SS-Solar por favor, envía nuevamente el archivo al correo coding.up.my.future@gmail.com sin cambiar el nombre del archivo ni alterar la estructura de este. Una vez se corra de nuevo la calificación automática deberías obtener un correo con tu nota, si esto no ocurre, por favor vuelve a copiarnos en este hilo.

Muchas gracias!

**Comment by SS-Solar** [comment]
Hola, ya hice él envió otra vez de 2 trabajos no me ha rebotado esta vez, estaré pendiente ante cualquier eventualidad
