### ISSUE TITLE
Duda con devolución de Taller 1 

### ISSUE THREAD

**Issue by santiagocano298366** [codingupmyfuture/bootcamplinuxpython#30]
Buenas tardes. 
¿Alguien me podría explicar que son estos errores? 
La mayoría no los entiendo 

![Screenshot_2023-08-17-16-06-54-680_com.google.android.apps.docs.jpg](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/83661332/cc04b2ac-20b4-494b-8743-3eb570bd2fb3)

**Comment by keljozap** [comment]
Hola @santiagocano298366 quisieras por favor compartir el notebook que enviaste para validar tu código. Muchas gracias!

**Comment by santiagocano298366** [comment]
> Hola @santiagocano298366 quisieras por favor compartir el notebook que enviaste para validar tu código. Muchas gracias!

https://drive.google.com/file/d/1Q9MAR7SJvMSiDa1GIXfHtPy865Oces6O/view?usp=sharing

Aquí puedes descargar el archivo

**Comment by keljozap** [comment]
Hola @santiagocano298366 he revisado tu notebook y efectivamente tienes varios errores.
Punto 1.
El enunciado
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/13422ca4-c4de-4c25-bdd8-507405bdc6b4)


Tu respuesta
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/dd8bd8cd-33c8-4e3b-90c7-6364c9ace6eb)

Se piden usar en una variable comillas dobles y en la otra sencillas y tu notebook solo usa comillas dobles, por lo tanto no cumple con el ejercicio.


Punto2.
En el ejercicio se pide que uses el mensaje que esta ingresando en la función como parámetro de entrada, tu estas creando una variable nueva y más importante, no estas usando el return de la función.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/827fbd32-9a7a-4bec-8569-8038538e6b89)

He explicado algunos de tus errores, por favor revisa los conceptos vistos en clase y reestructura tu código.

Espero haber sido de ayuda.

**Comment by Josjisut** [comment]
@santiagocano298366  En cada uno de los puntos (Los encuentras mas abajo en ese PDF), te aclara que es lo que tienes mal, te dice cual fue tu respuesta y cual era la respuesta esperada.
