### ISSUE TITLE
Problema con el nombre del taller 3

### ISSUE THREAD

**Issue by mariafrancodev** [codingupmyfuture/bootcamplinuxpython#36]
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/42823670/3da2b97c-37d5-4d1c-8534-6b0e501c2462)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/42823670/44f82e5d-5ce7-41cf-96bd-878fc8c29eb5)

**Comment by luisvasv-teck** [comment]
issue repetido, revisar #26
