### ISSUE TITLE
PROBLEMA CON TALLER #1

### ISSUE THREAD

**Issue by santiagocano298366** [codingupmyfuture/bootcamplinuxpython#37]
Buenas tardes. 
Modifiqué el primer taller con algunas correcciones que me han dicho  por aquí, solo que tengo una duda con el punto número 3, me dice que la respuesta esperada debería de ser la siguiente:

<img width="625" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/83661332/16505fed-db2d-40fe-9dff-d99fd9576571">

Dice que la respuesta debe de ser Estoy aprendiendo Python, pero en la funcion dada (la cual no modifique en ningun momento), no aparece en ningun lado la palabra Python

<img width="211" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/83661332/72132a0c-cc40-4cd9-bcbd-47690e600d18">

Lo mismo con el punto 5, el cual dice:

`Escribir dentro de la función function la lógica para imprimir 4 veces el input que se entrega en el parametro string . Recuerde que el tipo de dato entregado por el parametro string no siempre será string.`

Lo que entiendo es que deberia imprimir 4 veces consecutivas la palabra Python, este es el error que me tira el doc:

<img width="618" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/83661332/88e0a31e-e464-43c9-987b-8709e2fb6f70">
No me queda claro muy bien esto

Me gustaría saber que problema hay, debido a que cumplo con la función dada.
Estaré atento a cualquier respuesta.

**Comment by Elioric** [comment]
Buenas tardes, Santiago. El string "Estoy aprendiendo" es un string de prueba que se nos da en el ejercicio para tener un concepto de qué se le está pasando a la función a evaluar. Como tal, no es el string con el que se hace la prueba automatizada.

Verás en las respuestas de control y del estudiante que lo que hace el bot es enviar un string cualquiera para hacer la prueba (esto con la intención de validar que no se haya enviado de forma hardcodeada la respuesta predefinida). Se hace uso de 3 strings diferentes y cada uno debería retornar lo que propone o muestra el control. No sé si me explico correctamente.

**Comment by santiagocano298366** [comment]
Esta bien.
Hay algun problema si uso el string de prueba? 
Si es así, entocne sno se bien por que me tira el ejercicio como malo

Adjunto mi solución:

```
def function(string):
    mensaje : str = "Python"
    multi :str = mensaje*4
    return multi



function("Python")
```

Y  tampoco comprendo entonces, por que me arroja mal el ejercicio de "Estoy aprendiendo"

```
def function(string):
  texto : str = "Estoy aprendiendo"
  pos_cinco: str = texto[:5:1]
  print("String hasta la posicion 5: ", pos_cinco )
  pos_seis: str = texto[6::1]
  print("String desde la posición 6: ",pos_seis)
  invertido: str = texto[::-1]
  print("String invertido: ",invertido)
  saltos_tres:str = texto [::3]
  print("Todo el string pero en saltos de 3: ",saltos_tres)
  return pos_cinco, pos_seis,invertido, saltos_tres


function("Estoy aprendiendo")
```

**Comment by Elioric** [comment]
En ```def function(string)``` se está pasando el string que se debe evaluar. No lo debes quemar en tu código... Prueba haciendo ésto:

`mensaje:str = string` -> string es el nombre del parámetro que se está pasando a la función.

Igual en el otro ejercicio:
`texto:str = string`

Así, no importa qué valor se me pase, siempre va a cumplir la lógica que se espera de tu código.

**Comment by santiagocano298366** [comment]
Está bien. Lo haré 
Muchas gracias!
