### ISSUE TITLE
Problema con el ejercicio # 7 del taller PYPLVL1_PYLVL1ASTR_E10_P10

### ISSUE THREAD

**Issue by alejandrazapatap** [codingupmyfuture/bootcamplinuxpython#38]
Tengo duda en cuanto a este punto ya que me devuelve que no elimino los espacios, incluso le agregue un espacio y le hice un len para ver si era error en mi codigo y me devuelve correcto, depronto alguien me podria ayudar. Muchas gracias.

este es mi código: resultados_solicitados = len(string.upper()), string.lstrip(), string.lower(), string.title(), len(string.strip())

(7, 'Python ', 'python ', 'Python ', 6)

**Comment by Elioric** [comment]
Hola. Por qué envías la longitud en el resultado? Cuál es la devolución original?

**Comment by alejandrazapatap** [comment]
no la longitud no la envie, solo la puse hay en el ejemplo para validar que efectivamente esta borrando los espacios

**Comment by Elioric** [comment]
Debes quitar todos los espacios del texto, el método string.strip() sólo quita los espacios al inicio y al final de la cadena. El ejercicio pide que se quiten todos. Puede hacerlo con una cadena de prueba que no sea "Python", usa las de la revisión

**Comment by alejandrazapatap** [comment]
Ahh entiendo, ahora si ya me cuadra. jajaj muchas gracias😊
