### ISSUE TITLE
Problema con el nombre del taller #3

### ISSUE THREAD

**Issue by Juand1199** [codingupmyfuture/bootcamplinuxpython#40]
Hola! Al igual que otros compañeros tuve un problema con el envío para posterior calificación del taller #3, ya que, el bot me diagnosticó como invalida la entrega al parecer por un error de nombre, pero la realidad es que no hice ninguna modificación a este en el archivo original.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/140764066/e39d2da0-bfd2-48bb-97c8-dfe796f8dca5)

**Comment by estebanosorio** [comment]
Tengo el mismo problema, realicé la entrega una segunda vez descargando y volviendo a escribir las soluciones de los ejercicios creyendo que pudo haber dañado algo en el formato y me volvió a sacar el mismo error.

**Comment by luisvasv-teck** [comment]
issue repetido, revisar #26
