### ISSUE TITLE
Entrega invalida taller # 1

### ISSUE THREAD

**Issue by Warteaga22** [codingupmyfuture/bootcamplinuxpython#41]
Hola lo he enviado dos veces y me dice inválido.
(El cuaderno enviado contiene un número de celdas mayor o menor en comparación con el trabajo asignado.) correo Arteagavane15@gmail.com

**Comment by luisvasv-teck** [comment]
Los notebooks no pueden ser modificados en el sentido que no se pueden agregar o quitar filas del notebook. Posiblemente, tu error es porque hiciste alguna de las dos previamente mencionados.

Descarga el archivo original y realice la comparación para ver que fue lo nuevo que adicionaste
