### ISSUE TITLE
Problema con nombre de los talleres 1 y 2

### ISSUE THREAD

**Issue by Marilyalcaraz** [codingupmyfuture/bootcamplinuxpython#42]
Buenos días, se me esta invalidando la entrega de los talleres 1 y 2 debido a que los identificadores de los notebooks no concuerdan, pero haciendo la respectiva revision los tengo nombrados tal cual se nos indico 
Adjunto evidencia:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141260969/2443c62f-7188-4ddb-9261-df7e5318ae0b)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141260969/0d9e3072-87a1-4f02-955d-6d20a129093c)

**Comment by luisvasv-teck** [comment]
por favor, crear un nuevo correo y enviarlo de nuevo
