### ISSUE TITLE
Problema de correo para envío-recepción de trabajos

### ISSUE THREAD

**Issue by Cesc29** [codingupmyfuture/bootcamplinuxpython#44]
El domingo 20 de agosto envié los dos primeros talleres - strings y booleanos- y no llegó correo de recibido por parte del robot (ni siquiera en SPAM), hoy martes 22 de agosto volví a mandar los talleres ante la instrucción de volver a mandar correos (cada taller lo mando aparte en un correo nuevo) y aún no recibo correo respuesta, sin embargo, si me están llegando las invitaciones a las clases y otros correos.

PD: los archivos los envío en formato .ipynb, no se si esto afecte

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/140763403/c5242c48-a7a7-47dd-aa0d-6600622d5b99)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/140763403/116a465b-06dc-4268-b690-0b1206d53393)

**Comment by luisvasv-teck** [comment]
Experimentamos varios bloqueos en la aplicación con algunos usuarios mientras el bot realizaba calificación automática. Al analizar las causas de los retrasos, encontramos lo siguiente:

Algunos estudiantes están utilizando la función 'input' en los ejercicios (lo cual no se solicitaba en el ejercicio y recuerden que esta función requiere intervención humana).

Los estudiantes que aparecen en la imagen deben corregir sus entregas; para todos los demás, recuerden no utilizar 'inputs'.

![telegram-cloud-photo-size-1-5129959898585606899-y](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108821097/78fc4806-0cba-4c05-bb97-f07e30c9f91c)
