### ISSUE TITLE
¿Podría importar librerías?...¿Cómo?

### ISSUE THREAD

**Issue by davidcrvDev** [codingupmyfuture/bootcamplinuxpython#45]
Me encuentro realizando el taller de Tuplas, quisiera saber si puedo implementar librerías de python para el desarrollo de mi taller. En caso de que sí, ¿En donde puedo poner la línea de código para importar la librería?
![imagen_2023-08-22_205956666](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/142955932/596a3185-f954-4048-a321-5d69df9735b3)

**Comment by JoseJulianMosqueraFuli** [comment]
Para el taller creo que no se pueden implementar librerias externas hasta el momento, debido a que en colab modificariamos el tamaño de las celdas y el bot retornaria el taller sin calificar.
Debido a que deberíamos instalarlas en el colab con pip install
Más por curiosidad, un ejemplo sería:
```
pip install requests
```
![Captura de pantalla 2023-08-22 215051](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/d024b4f8-88b5-4872-ae51-c9ea0d28c7da)

@luisvasv-teck @codingupmyfuture 
Podrían brindarnos mayor información al respecto, si me equivoco.
Gracias 😄
