### ISSUE TITLE
Preguntas taller 3

### ISSUE THREAD

**Issue by SS-Solar** [codingupmyfuture/bootcamplinuxpython#47]
Teniendo en cuenta que la solución dicta que el valor debe ser "23567bt" (según la corrección del taller (imagen1)), me queda la duda de por que? si la cadena de string Abc235435786strzh, salteada cada 2 saltos (como muestra en la prueba(imagen 2)) da "23567btz"  organizada de manera correcta. 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/72994010/0275a06f-d6fd-480f-9f28-88ddf62f5650)
imagen 1
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/72994010/32c0083f-cb9e-4992-af9a-17c300fffe32)
Imagen 2

**Comment by davidlopez-190** [comment]
Tengo la misma pregunta

**Comment by SS-Solar** [comment]
pero si se pone a ver, primero a que lista se le calcula eso? a la lista inicial de string que es el que da la entrada (string) o a la que uno crea a partir de quitarle el inicio y el fin.
Si es la primera estaría bien por que se tienen 17 posiciones ( de 0 a 16), por lo tanto la mitad sería 8(redondeando hacia arriba) '23567btz' cumple
Si es la segunda quitándole el inicio y el fin "bc235435786strz" son 15 posiciones la mitad serian 8 redondeado hacia arriba, por lo tanto también estaría correcto afirmar que '23567btz' cumple.

**Comment by Elioric** [comment]
Las mitades fraccionarias no se deben redondear hacia arriba sino hacia abajo, sólo se toma el valor entero. Porque si la mitad de 15 es 7.5 y tú agregas un octavo elemento, habrías excedido la longitud de la mitad de la lista.

**Comment by Lera2597** [comment]
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/116927336/9d982275-97ea-47bd-817a-310e255fa85c)

**Comment by Lera2597** [comment]
Puede solucionar el problema para las dos primeras entradas de la imagen, pero para la tercera no me funciona. Asi que realmente tengo misma duda ustedes.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/116927336/37881c18-6e11-43f6-b098-9c861a2e6c68)

**Comment by EstebanSancho** [comment]
Ok, pero en ese caso como controlo la longitud de la lista con los saltos sin usar condicionales? Porque si le pongo un IF podría limitar su crecimiento, pero no veo muy claro como hacerlo sin este condicional

**Comment by Juand1199** [comment]
> de acuerdo a lo que entiendo del punto 4, se debe tener en cuenta que al momento de extraer los caracteres en saltos de N, la cantidad de caracteres extraídos no pueden ser mayores a la mitad del tamaño de la lista
> 
> ![image](https://user-images.githubusercontent.com/41384432/262708792-036f0450-1db7-466d-9b86-0f111fff91e3.png)
> 
> de esa forma daría el resultado esperado por el validador

Para tener en cuenta esto habría que usar condicional necesariamente, no?

**Comment by EstebanSancho** [comment]
No. Hace un momento tuve la misma duda pero encontré una manera de hacerlo sin condicionales.
Puedes hacer un slice que inicie en 0 y que termine en la mitad de la longitud del string modificado (sin el primero y el último valor)

**Comment by Elioric** [comment]
Así es @EstebanSancho, cuando se crean slices no es necesario saber la longitud de la lista, puesto que si el slice que defines es mayor a la longitud, simplemente va a devolver todos los elementos hasta el final y si es menor, toma la porción de la lista (una sublista). Aplica igual para los demás iterables como en el caso de los strings.

```
lista = [1,2,3,4,5,6] # longitud 6
slice1 = lista[1:4] # [2,3,4]
slice2 = lista[1:10] # [2,3,4,5,6]
```
