### ISSUE TITLE
Pregunta 01 - Taller #3 Listas

### ISSUE THREAD

**Issue by Elioric** [codingupmyfuture/bootcamplinuxpython#48]
Buen día, 

@codingupmyfuture tengo dudas respecto a la descripción del primer punto (01) del taller #3 manejo de Listas. 

Se solicita filtrar los elementos por índices impares, los cuales corresponderían a los índices 1,3,5,7,...n*2+1... Sin embargo, la respuesta de control retorna los resultados para los índices pares 0,2,4,6,...n*2, lo cual es incorrecto con respecto a lo que se solicita en el ejercicio siguiendo el estándar de numeración de índices de Python de 0 en adelante.

Entrada: `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]`

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/6803f732-a742-4e55-86d7-25ddf6ba1a90)

En la entrada, los índices impares corresponden a los elementos pares. El control devuelve los números impares que se encuentran en los índices pares.

Agradezco la ayuda para solventar la duda.

**Comment by joamza** [comment]
Tengo la misma duda, debido a que la respuesta de control lo que hizo fue imprimir los valores impares que se encuentran en las posiciones pares

**Comment by manferjam0508** [comment]
Buenos días

Esta es la misma duda que tengo, sobre que parámetro trabajaría para el desarrollo del primer punto, por que aparece dentro de la función, si se genera la cantidad de listas con 30 elementos o una cantidad que multiplique por 30, cual tomo de referencia:
def function (lista) o function(['*'] * 30)?

**Comment by melenabelt** [comment]
El ejercicio está mal formulado porque dice que los ÍNDICES deben ser impares y no es así porque la máquina muestra lo contrario.

**Comment by Warteaga22** [comment]
![1063eec7a56dac74a80fc37291ba21d3](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/90656337/759c2f8a-6313-4ba8-a833-77c69a868e02)

**Comment by juli-amezquita** [comment]
Hola @Warteaga22 este ejercicio pide retornar los elementos de índices impares de la primera mitad de la lista, al principio la respuesta control estaba retornando los elementos de índices pares, lo que era incorrecto porque eso no es lo que pide el ejercicio, sin embargo, esto lo corrigieron hace unos días, y ahora sí, la respuesta control está tomando los índices impares, como debe ser. Solo cámbialo a que te tome los índices impares y ya no deberías tener problemas.
