### ISSUE TITLE
Duda punto 2 taller 3 Listas

### ISSUE THREAD

**Issue by joamza** [codingupmyfuture/bootcamplinuxpython#49]
Buenos días, tengo la siguiente inquietud frente al resultado del taller 3

en el punto 2 

la respuesta de control indica que el resultado esperado es: 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/41384432/4971102f-17b3-4b4a-9f39-dbc72fadd25a)

mi duda es por que los últimos 7 ítems esperados son 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/41384432/70c52825-3999-40d0-a53d-b8828800118b)
si el taller indica que: Para el ultimo cuarto de la lista solo tomar los elementos en posiciones pares, al observar la ultima grafica, el ultimo cuarto de la lista los elementos en posiciones pares serian : 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/41384432/c91ea07e-56c3-4b35-9ef0-71e15d17dcc5)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/41384432/3a5b17b0-6765-4602-a6ef-109aee435a75)

**Comment by Elioric** [comment]
La lógica con la que lo veo es que el cuarto cuarto de lista si lo separas de la lista original, su primer elemento empieza en el índice cero (0) que es un número par, 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/4a2a88c5-826c-468f-8da9-250dd1ce7488)
pero en la lista original, el número 46 se encuentra en lista[45] que es un índice impar, por lo cuál no estaría tomando el valor que corresponde a índices pares en la lista original. Aquí, los índices pares corresponden a elementos impares.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/f083a1c5-0986-48b7-9db0-1ec6f766347c)

**Comment by melenabelt** [comment]
El ejercicio está mal formulado. Si tenemos una lista con los números del 1 al 60 el último cuarto empieza en 47 y según la máquina el 0 es par, así que los índices pares de ese último cuarto serían 47, 49, 51... El problema está en que cuando la lista está del 1 al 50 según la máquina el primer número es 40 cuando claramente siguiendo la misma lógica debería ser 38.

**Comment by keljozap** [comment]
Chicos buenas tardes. El ejercicio dice "Dada una lista de N >= 50 elementos", nunca dice que sean los primeros 50 números, de hecho dice N>= 50, es decir son 50 elementos, que pueden ser los primeros 50 números naturales, los primeros 50 números pares, etc.

Para el último cuarto de la lista se indica "Para el ultimo cuarto de la lista solo tomar los elementos en POSICIONES PARES. No dice, los números pares, dice posiciones pares. Esto puede hacerse usando rebanado de listas.

**Comment by melenabelt** [comment]
si la lista está con los números del 1 al 60 los cuartos son:
1. 1 al 15
2. 16 al 30
3. 31 al 45
4. 46 al 60

Teniendo en cuenta esto, la respuesta correcta del código dice que debería dar como resultado: 47, 49, 51, 53, 55... (tomando los índices IMPARES)

<img width="556" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/cba965f6-61be-4bde-9822-13dacfec91dd">

Si hacemos el mismo ejercicio con una lista de 50 elementos, sería así:
1. 1 al 12
2. 13 al 24
3. 25 al 36
4. 37 al 50

Por tanto, la respuesta correcta debería ser : 38, 40, 42, 44, 46, 48 y 50 y no 40, 42, 44, 46, 48, 50]

Puntos importantes:

- El ejercicio dice que tomar las posiciones pares, pero esto no está calificándose así porque las posiciones pares en el la lista del 1 al 60 debería ser: 46, 48, 50... si tomamos el 0 como par
- La respuesta según el código usando la lista de 50 elementos estaría empezando en el índice 3, dejando por completo los índices del 0 al 2 correspondientes a 37, 38 y 39

**Comment by Elioric** [comment]
>La respuesta según el código usando la lista de 50 elementos estaría empezando en el índice 2, dejando por completo los índices del 0 al 1 correspondientes a 37 y 38

La razón por la que está dejando por fuera al 37 y al 38, es porque no se encuentran entre los últimos 12 números de la lista.
Prácticamente está tomando el último slice como `lista[-12:]` que corresponden a los últimos 12 números de la lista, esto excluye al 37 y al 38. La lista de cuarto final queda `[39,40,41,42,43,44,45,46,47,48,49,50]`... Por eso representa un conflicto el hecho de que los cuartos de una lista de longitud 50 correspondan en longitudes de 12 + 12 + 12 + 14

Conclusión:

- Todas las listas de longitudes que no sean divisibles por 4 de manera exacta, no tomarán todos los valores de la lista original.

**Comment by juli-amezquita** [comment]
Hola compañeros, yo estoy de acuerdo con @melenabelt 

Si tomamos en cuenta la teoría de slicing (rebanada) de listas de python `mi_lista[inicio,fin]`: (1) el índice de inicio es inclusivo (se incluye en la rebanada), (2) el índice de fin es exclusivo (el elemento en este índice no se incluirá en la rebanada) y (3) la cuenta debe empezar desde 0.

Teniendo en cuenta la lista que nos entregaron en el ejercicio (desde 1 hasta 60), los cuartos de lista estarían compuestos por 15 elementos y quedarían conformados de la siguiente manera: 

![Captura de Pantalla 2023-08-23 a la(s) 4 22 01 p m](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/7b017ea6-7d96-48c9-bb6a-c2bedae06ccb)

Entonces tomando el último cuarto de la lista, las posiciones pares serían las de color amarillo:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/64dc0e91-aaac-4d94-9c68-40831fd9d9b6)

Por ende, la respuesta correcta a lo que nos piden, sería la siguiente y no como está en el pdf, ya que para el último cuarto de lista, el ejercicio nos pide las posiciones o los índices pares: 

![Captura de Pantalla 2023-08-23 a la(s) 6 17 15 p m](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/3e0a278e-360f-4a53-872d-fad59a8fd8a4)


![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/1d051eae-ef11-4430-b20e-d51e8d2d59bd)

De la misma manera, para la segunda lista con la que valida el bot (desde 1 hasta 50), los cuartos de lista estarían conformados por 12 elementos (teniendo en cuenta que hacemos una división entera), excepto para el último cuarto:

![Captura de Pantalla 2023-08-23 a la(s) 4 36 12 p m](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/4a21eb84-3be6-410e-a5b2-7658c269dc50)

Entonces, para este caso, si tomo el último cuarto de la lista, las posiciones pares serían las que están resaltadas en amarillo:

![Captura de Pantalla 2023-08-23 a la(s) 5 22 48 p m](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/bb0582eb-c56b-4f13-b772-3a387093f181)

Por ende, la respuesta correcta a lo que nos piden **_(“para el ultimo cuarto de la lista solo tomar los elementos en posiciones pares”),_** sería la siguiente y no como está en el pdf: 

![Captura de Pantalla 2023-08-23 a la(s) 5 25 44 p m](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/68128049-38ad-405b-94bd-311762434faa)

![Captura de Pantalla 2023-08-23 a la(s) 5 35 03 p m](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/77032671/029933fb-ed8b-4156-a6f0-ba9710fb1347)

**Comment by EstebanaOrozco** [comment]
Hola, tengo el mismo problema que todos, considero que la aclaración de @codingupmyfuture @luisvasv-teck es urgente.
Por mí lado apoyo la forma en que lo ve @Elioric , lo importante es la posición orginal de la lista y no el item ni la nueva posición que toma al hacer el slicing, sin embargo bajo esta lógica es imposible que el código funcione para los dos casos que prueba el bot, por que tal como lo decía @Elioric en su segundo aporte el control bota 2 items en su respuesta cosa que no tiene lógica alguna bajo las reglas que propone el ejercicio.

**Comment by Elioric** [comment]
@juli-amezquita lo que dices que cada rebanada de lista empieza en 0  y que 0 es un número par, es cierto. Sin embargo, en la lista original, cada cuarto a excepción del primero comienza en un índice impar. Por lo tanto en la lista original, lo elementos impares se encuentran e índices pares.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/70f8c222-e5fc-4307-9386-f6a80a2fd1b3)
[Imagen 1] Los índices están con respecto a la lista original y no a la lista rebanada, ya que nos interesa es la lista en su totalidad.

La lógica anterior no aplica para listas de longitud Len%4 != 0 (longitudes que no son divisibles entre 4 de forma entera, como es el caso de la lista de longitud 50)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/63201190/8715773d-ea7c-49ab-8fe6-4a6555cea46a)
[Imagen 2] Ejemplo de lista no divisible entre 4, sobran elementos

El ejercicio debe ser revisado, puesto que no habría una respuesta universal según lo que hemos estado planteando en éste hilo.

**Comment by melenabelt** [comment]
Ya logré llegar al resultado esperado, pero igual importante recalcar que no se están tomando los índices pares como dice el enunciado sino los impares como muestra Control.

**Comment by edallanpoe** [comment]
Cordial Saludo,

Con respecto a las dudas frente a las dudas generadas por el ejercicio:

1. El enunciado del ejercicio está solicitando trabajar con las posiciones de los elementos 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/105033576/e2e061aa-c15f-4bcc-bf7a-1c0707a6e565)
En este caso los elementos no son de interés para el ejercicio, solo las posiciones de la lista.

2. Acorde con el primer punto de esta explicación, se tiene como parametro de entrada `lista = mas o 50 elementos`, para ésta explicación se utiliza la lista de 50 elementos
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/105033576/e080e671-684e-40d6-9f4b-19135311859b)
Tienen que tener en cuenta que sí bien los elementos son del 1 al 50, no es de interés para la solución ya que se tienen 50 elementos con posiciones 0 a 49, son las cualidades de las listas que dictan que la primera posición de toda lista comienza en 0.

3. Con respecto a la partición de la lista en 4 cuartos, por lo tanto se puede hacer de varias formas:
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/105033576/a07b72e8-2ecb-4dfe-9776-537ddf8c7b59)
Como se observa en la imagen se hacen 3 operaciones distintas para obtener la longitud del cuarto, teniendo que todas dan el mismo resultado, por el redondeo que hace la conversión a `int` del `float` resultante de la división, la propiedad de los int dicta que cuando se realiza una conversión de `float` a `int` no se redondea a 0, se corta el valor hasta donde esté la **coma flotante** o mejor dicho se **ignora** el valor del decimal.

¿Por qué se tiene que utilizar un `int` para determinar la longitud del cuarto?
Porque los slices en lista solo permite especificar la posiciones en enteros, de lo contrario se genera una excepción:
<img width="501" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/105033576/6df7db81-d8c5-46d4-8a8d-7068541decf8">

4. Una vez obtenida la longitud del cuarto, en ningún momento en el ejercicio se solicita que explicitamente se debe cubrir toda la lista o que se utilicen longitudes disparejas cuando el numero resultante en los cuartos no es exacto, por lo tanto es inferible que se debe trabajar con 4 porciones de la lista de igual longitud.

Se explica correctamente en este comentario: [Elloic](https://github.com/codingupmyfuture/bootcamplinuxpython/issues/49#issuecomment-1690721870)

6. con respecto al punto 4 del ejercicio, se solicita que se trabaje con el **último** cuarto, por lo que se entiende que sí la longitud del cuarto es 12, se debe trabajar con las últimas 12 posiciones de la lista, no  con las posiciones que le siguen al tercer cuarto.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/105033576/89282ed7-728c-4e57-9e6a-72a523d67ed9)
Se aclara que para efectos del ejemplo mostrado en la imagén se utiliza la lista de 50 elementos.

7. Continuando con el punto 4 del ejercicio, luego de obtener el **último** cuarto, es correcta la logica expresada en los comentarios: 
* [melenabelt](https://github.com/codingupmyfuture/bootcamplinuxpython/issues/49#issuecomment-1690600179)
* [juli-amezquita](https://github.com/codingupmyfuture/bootcamplinuxpython/issues/49#issuecomment-1690769670)

_Demostración de la lógica_
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/105033576/7c81c96d-244b-4ea9-b15d-2661350f2ccd)

**Se corrige la lógica del punto 4 del ejercicio y se enviará nuevamente el notebook a los estudiantes.**

Dicho lo anterior...

Felicitaciones y muchas gracias a quienes se toman la tarea de explicarles a los demas estudiantes, y resaltar cuando los ejercicios tienen errores.

Se corregirá y se volverá a enviar en el menor tiempo posible.
