### ISSUE TITLE
Solicitud de certificado de participación 

### ISSUE THREAD

**Issue by Ana-0811** [codingupmyfuture/bootcamplinuxpython#51]
Hola equipo! 

Debido a que estoy pidiendo un permiso en la empresa donde trabajo para poder asistir al curso, les solicito una carta donde conste que estoy inscrita en el curso y sus horarios.

Dejo mis datos:
Ana Maria Arroyave 
CC 1039456943 
anam.0811@gmail.com

Mil gracias!

**Comment by luisvasv-teck** [comment]
Escríbele porfa a dliza@softserveinc.com
