### ISSUE TITLE
Error a reproducir el ejercicio 1 del taller de Tuplas

### ISSUE THREAD

**Issue by Cris-Cod** [codingupmyfuture/bootcamplinuxpython#52]
Buenas Tardes

Al realizar el envio del taller de tuplas en el primer punto la función que recibe un parametro es n pero creo que el bot esta tomado los parametros que estan en la fucion del taller que son (("A","A"), ("A","A")) y creeria que esa es la respuesta, cuando el parametro es 2 y si reporduce asi el caso con los datos que estan en el taller se genera un error.

![ejercicio 1 tuplas](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/75702892/7a2ac8b9-2709-441a-9e1e-5e8d59d60cc3)

**Comment by EstebanaOrozco** [comment]
Hola, como la función se ve que está mal llamada, yo simplemente cambié el input para que fuera un número y no la matriz de tuplas, así el ejercicio si va a correr y no te quedas estancado.

**Comment by EstebanaOrozco** [comment]
@codingupmyfuture @luisvasv-teck

**Comment by luisvasv-teck** [comment]
Se realizaron algunas actualizaciones a la descripción de los ejercicios, para más detalle mirar este mensaje en Telegram: https://t.me/c/1786701113/919/1414
