### ISSUE TITLE
Respuesta del taller de tuplas del punto 3

### ISSUE THREAD

**Issue by Cris-Cod** [codingupmyfuture/bootcamplinuxpython#53]
Buenas Tardes

El punto 3 del taller de tuplas indica que a partir de una tupla de 5 elementos distribuirlas en 3 variables, se distribuyen de la siguiente forma la primer variable es un String, la segunda una lista de 3 elementos y la tercera es otro string, pero la respuesta del taller esta divido de la forma primer variable es un string, segunda variable es un string y la tercera es la lista, pero en el ejercicio no indica que se deberían posicionar de la forma variable string, string, lista, porque creo que las variables se pueden crear indiferente el orden
![Ejercicio 3 Tuplas](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/75702892/1a6fdf09-e40e-48e5-b88f-c7121ff2f6d2)

**Comment by alejandrazapatap** [comment]
me sale igual 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/68ecac2b-5133-4f8e-9104-8d81985facf9)

**Comment by alejandrazapatap** [comment]
A mi lo que me sale es que el ejercicio esta bueno pero a mi me lo marcaron como malo 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/28427d5d-094c-4a03-9734-31b57d1492f3)

**Comment by melenabelt** [comment]
Así funciona el desempaquetamiento de tuplas. Si desempaquetas una tupla, aquella variable que cuente con más de 1 elemento es una lista. Por eso es que A y B son strings porque está contenido cada string en una variable, mientras que C, D y E están en lista porque están todos 3 contenidos en una variable después de desempaquetar la tupla.

**Comment by Cris-Cod** [comment]
Claro cuando se desacopla con unas variables menores a los elementos de la tupla se va a generar una variable que va a ser una lista, pero mi duda es que si la lista puede ser creada en la primer variable o segunda variable, no siempre debería quedar al final?

**Comment by melenabelt** [comment]
Si te fijas en las respuestas de la máquina verás que esa lista siempre está al final. Con lo que nos han mostrado debe quedar al final, pero no sé si hay alguna forma de hacerlo diferente; busqué bastante y no vi otras opciones.

**Comment by luisvasv-teck** [comment]
Se realizaron algunas actualizaciones a la descripción de los ejercicios, para más detalle mirar este mensaje en Telegram: https://t.me/c/1786701113/919/1414
