### ISSUE TITLE
Fallo en la ejecución

### ISSUE THREAD

**Issue by hrriverar** [codingupmyfuture/bootcamplinuxpython#54]
Buenas quisiera saber a que se debe el error que arroja el bot calificando cuando dice: No se puede resolver, fallo en la ejecución. Siendo que cuando yo lo corro me devulve los valores pedidos y no se en que parte estoy mal por esa misma raz´n, el bot no arroja la parte que estoy mal. Gracias

**Comment by keljozap** [comment]
Hola @hrriverar como estás? espero que bien, quisieras compartirme el notebook que estas realizando con el que tienes el problema? o una captura del ejercicio al que te refieres para saber cual es el problema.

Gracias!

**Comment by luisvasv-teck** [comment]
Amablemente solicitados enviar más detalle para poder validar, gracias.

**Comment by hrriverar** [comment]
Hola  buen día aqui esta mi notebook
https://colab.research.google.com/drive/19UZs7IRfkiLzN1UfcBWy4iLSER7lMqOA

**Comment by hrriverar** [comment]
Esta es la imagen del error, tengo 5 ejercicios con el mismo error, ya lo he enviado 3 veces quitando y o agragando cositas
pero nada siguen apareciendo los mismos errores, también  los pase a un nootebook nuevo y tampoco.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/134157669/df9ffb63-2757-4e9a-b6bb-0d0f63227c33)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/134157669/49ad3479-5434-46d3-8c1d-4c8002dbec5b)
