### ISSUE TITLE
Duda PYLVL1BBOOL-03

### ISSUE THREAD

**Issue by mamulcuer** [codingupmyfuture/bootcamplinuxpython#55]
Buenas, 

¿A alguno le dió este punto 3 en el taller 2 de Booleanos? 

Este es el segúndo intento de voler a generar el ejercicio la primera vez puse z = 5 == 5, que imprime true  y me la marcó tambien como mala, como ven no doy uso de > o < como dice el ejercicio.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/114958762/1031c040-9976-4407-9771-f7a00ef22f26)

El resultado de la ejecución es la siguiente: 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/114958762/46044875-37a2-4d83-9721-89cecc8c5755)

**Comment by keljozap** [comment]
Hola @mamulcuer buenos días, el ejercicio solo te esta pidiendo hacer una comparación y tu estas realizando una asignación de valor y una comparación en la misma instrucción. Basta con algo simple como print(1==1). Y listo!, no tienes que asignar el resultado a nada, puedes hacerlo directamente en el print. Espero resolver tu duda.

**Comment by JoseJulianMosqueraFuli** [comment]
Hola @keljozap, aunque tu propuesta presenta una solución más sencilla, también parece haber un posible error al asignar una comparación a una variable y tratar de imprimirla. Ambas aproximaciones deberían funcionar de manera equivalente, pero es posible que exista otro error en el código.

**Comment by keljozap** [comment]
Hola @JoseJulianMosqueraFuli, sí, de hecho, por eso le indiqué que había algo extraño en su sintaxis, y si de hecho lo haces no imprimiendo sino usando un return tienes un error de sintaxis como el siguiente: 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/7c9a1274-b495-4e3b-820f-dd0cd68052fc)

Adicional, la solución es sencilla ya que el problema no está pidiendo la creación de una variable, solo se esta pidiendo que se realice una comparación sin usar los operadores < y > y esto puede hacerse directamente sin necesidad de una variable adicional.

**Comment by mamulcuer** [comment]
Hola chicos, muchas gracias por su ayuda. Pero el ejercicio sigue generandome mal:

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/114958762/24281587-8a6b-43d6-9dca-67ac97820d87)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/114958762/33e13551-b33d-4b91-8b47-f1f3026a6555)

El crear la variable afuera o dentro el print no debería generar ningun tipo de inconveniente, dado que es lo mismo, lo que veo es que no me toma ningun tipo de respuesta el programa.

Sigo la verdad muy confundido.

**Comment by mamulcuer** [comment]
Si, @JoseJulianMosqueraFuli l realizo directectamente desde Collab, la cosa es que es el único que me genera incovenientes, las otras respuestas creo una variable y luego la muestro con print.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/114958762/3ffcb049-164a-4919-b7e2-c1861d9ffdfe)

**Comment by keljozap** [comment]
Puedes compartir tu notebook para mirar que es lo raro?

**Comment by mamulcuer** [comment]
https://drive.google.com/file/d/1GIIvAJv418bnaxk4RRZiRRojg1xXpAGR/view?usp=sharing , si por supuesto.

**Comment by keljozap** [comment]
@mamulcuer listo, tenias un espacio al inicio de la palabra print compañero. En Python es muy importante prestar atención a los espacios y a las tabulaciones ya que el lenguaje es sensible a estos. Eliminalo y ya te deberia funcionar.

**Comment by mamulcuer** [comment]
¡Mil gracias compañero!
