### ISSUE TITLE
Error en la revisión en el taller PYLVL1EDICT-04 punto 3

### ISSUE THREAD

**Issue by JonathanProf** [codingupmyfuture/bootcamplinuxpython#57]
En el taller de diccionarios el enunciado sugiere realizar el procedimiento siguiente:

Dado un diccionario vacío: Agregue dentro de la función function los elementos email : [Sergio@gmail.com](mailto:Sergio@gmail.com) , celular: 123456 y modifique el valor de edad a 30

Dado lo anterior creo que hay un error en la respuesta de control del calificador automático ya que al comparar con el resultado esperado aparece la respuesta para la edad en 25 y no en 30 que debería ser el resultado luego de la modificación realizada a la edad

> {'nombre': 'Sergio', 'edad': **25**, 'genero': 'M', 'email': 'Sergio@gmail.com', 'celular': '123456'}

**Comment by Lera2597** [comment]
Estoy de acuerdo con @JonathanProf

**Comment by EstebanaOrozco** [comment]
Hola, vengo a hacer +1 a este issue. Esperamos que corrijan el calificador o cambiamos el return para que sea igual al que espera el control aunque no sea lo que pide el enunciado? @luisvasv-teck

**Comment by melenabelt** [comment]
Mismo error aquí.

**Comment by PalantirDagor** [comment]
Hola compañeros buenos días, detallando la respuesta del PDF que @EstebanaOrozco trae lo que puedo ver es que el valor de la llave 'celular' que esta esperando el bot es string y ese valor lo estan enviando numerico, por eso la respuesta es "La solución no superó a prueba: el dato de uno de los valores no es el esperado"
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56845586/a524ff9e-0c86-448b-a0eb-d77694b04b26)
