### ISSUE TITLE
Entrega Taller # 1

### ISSUE THREAD

**Issue by Danitcas** [codingupmyfuture/bootcamplinuxpython#58]
Realicé el taller 1 y recibí el correo con la calificación, hay unas respuestas que arrojan lo mismo que el bot, y aún así están malas, las otras corregí la forma de imprimir que se que a eso se debió el error pero ya no me deja enviar nuevamente el taller, lo he intentado varias veces y siempre sale "El cuaderno enviado tiene un número de celdas mayor o menos en comparación con el trabajo asignado". Incluso lo volví a descargar y sigue saliendo lo mismo, me podrían informar porfa que sucede y si se puede revisar, muchas gracias.

castanedapena20@gmail.com

**Comment by EstebanaOrozco** [comment]
Estás segura que no tienes una celda de más al final del notebook?

**Comment by Danitcas** [comment]
Si, muchas gracias, ya revisé eso también y la última celda es la del último código que se pide
