### ISSUE TITLE
Con respecto al taller actualizado de TUPLAS

### ISSUE THREAD

**Issue by davidcrvDev** [codingupmyfuture/bootcamplinuxpython#59]
Buenas tardes @luisvasv-teck @codingupmyfuture  Tengo una gran duda con respecto al nombre del nuevo archivo de tuplas
![imagen_2023-08-24_122142307](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/142955932/8d588581-27f8-4f56-a6e1-a1cbd5ed97f5)

Como se ve en la imagen, el archivo seleccionado es el de tuplas actualizado, mi pregunta es ¿No esta mal escrito el nombre del archivo?, ya que si nos fijamos en los demás archivos antes enviados al inicio de los archivos contiene "PYPLVL1_(....)" y si bien detallamos el actualizado no contiene esto mencionado.

Agradezco información al respecto para saber si los estudiantes podemos cambiar el nombre por cuenta propia o si en realidad el archivo si esta bien así tal cual.

NOTA: El archivo lo he descargado desde Telegram, ya que al email no me llego.

**Comment by Lera2597** [comment]
Al parecer presenta error para se evaluado 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/116927336/4bcca8db-2e2b-4169-96e8-edc653a96b71)

**Comment by davidcrvDev** [comment]
@Lera2597 Gracias por la imagen, entonces por obvias razones si toca corregir el nombre del archivo. Gracias Luis.

**Comment by luisvasv-teck** [comment]
Archivo corregido, el nombre debe ser PYPLVL1_PYLVL1DTUPLE_E5_P20.ipynb

**Comment by manferjam0508** [comment]
Buenas tardes:
Tengo una duda con respecto al punto 5 del taller de tuplas, lo estoy trabajando con el notebook actualizado; en el momento de poner los strings en la tupla, me frenan al definir el def como "__unused" y en function aparece como "none" (o null) y no me permite hacer la ejecución y la definición del ejercicio, me sale el siguiente error:

TypeError                                 Traceback (most recent call last)
[<ipython-input-42-2bb120785449>](https://localhost:8080/#) in <cell line: 14>()
     12 
     13 
---> 14 function(None)

[<ipython-input-42-2bb120785449>](https://localhost:8080/#) in function(__unused)
      4     apellido: str="Suarez"
      5     segundoap: str="Vasquez"
----> 6     nombre_tupla= tuple (nombre, apellido, segundoap)
      7     mensaje= f"Hola, mi nombre es {nombre_tupla[0]}, mi primer apellido es {nombre_tupla[1]} y mi segundo apellido es {nombre_tupla[2]}, mucho gusto"
      8     return mensaje

TypeError: tuple expected at most 1 argument, got 3}

Teniendo estas 2 limitantes, como lo podré corregir? estaré atento a sus comentarios, muchas gracias
