### ISSUE TITLE
hola no puedo ver el repositorio me sale un error!!!

### ISSUE THREAD

**Issue by Msandovalb282** [codingupmyfuture/bootcamplinuxpython#6]
Hola entro al repositorio y me sale un error!!!! nose a quien le pasa lo mismo. voy a ver el contenido del curso y me aparece el siguiente error!! estoy logeado con mi cuenta!!! gracias!!!

**Unable to render code block**

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/101159476/d8e995a6-88b8-400e-ae72-351d74a9b3e4)

por favor no soluciones de clonar y descargar,,, lo deseo ver desde cualquier laptop alguien que me pueda ayudar en realidad..

**Comment by aquirozg** [comment]
dale click a **contenido.curso** y luego en **003.notebooks** finalmente en

**Comment by JoseJulianMosqueraFuli** [comment]
# To solve this you could download the file.
![258250261-d8e995a6-88b8-400e-ae72-351d74a9b3e4](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/f20540b1-a508-4c09-a21b-a18a84d5d050)
## Another alternative is to download all the repositories in .zip:
1. First step in the repository, click on the button code.
2. Select Download ZIP and wait to download all the repository.
![1](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/292bc069-ec03-475c-ae0d-26118992d322)

Remember that solutions depend on what is your requirement.

**Comment by Msandovalb282** [comment]
> dale click a **contenido.curso** y luego en **003.notebooks** finalmente en **LVL1.01.intro.ipynb** ![image](https://user-images.githubusercontent.com/124750468/258253469-fd2847fa-cc81-44c9-a2c4-e896ecfa1452.png)

por esa ruta sale exactamente lo mismo...


![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/101159476/d8ee8659-122c-4c33-9c7b-224f44abe5a5)

**Comment by JoseJulianMosqueraFuli** [comment]
### In the same you could download the file, in this case, you could load it in collab this *.ipynb to work with them.
![1](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/c8b95ed7-bcf5-4198-aa15-4a3b05203f50)
Sorry I check the documentation and for the moment don't have any solution.
If I find someone.
