### ISSUE TITLE
error de ejecucion en la pregunta 02 de listas

### ISSUE THREAD

**Issue by jaca131** [codingupmyfuture/bootcamplinuxpython#61]
la respuesta del bot me dice esto y en mi computador si me ejecuta que puede ser este errror?
![fallo](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/127337474/f4523988-839c-42ca-8112-a70d2be493d5)

**Comment by keljozap** [comment]
Hola @jaca131 puedes compartir tu notebook o la respuesta de este punto para mirar que fue lo que pasó?
