### ISSUE TITLE
Duda punto 1 del taller de diccionarios

### ISSUE THREAD

**Issue by melenabelt** [codingupmyfuture/bootcamplinuxpython#62]
De acuerdo al enunciado debo imprimir y retornar _ambos_ diccionarios, pero según el ejemplo de la _Respuesta Esperada_ solo está retornando un diccionario 👇

<img width="691" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/22b95059-48ab-48ae-b350-984837c0fc2a">

Cómo sería el definitivo?

Gracias.

**Comment by JoseJulianMosqueraFuli** [comment]
No tuve inconveniente al reemplazar `return diccionario ->return a,b(ejemplo)` por mis diccionarios creados, lo mismo con el `print`.
Fue más una equivocación en la guia del taller.
