### ISSUE TITLE
Error en Taller de tuplas ejercicio # 2

### ISSUE THREAD

**Issue by alejandrazapatap** [codingupmyfuture/bootcamplinuxpython#66]
Hola, veo que hay un error en la calificacion del bot ya que el indica que no esta cumpliendo con la longitud, pero yo lo probe y esta exactamente igual
yo veo que mi ejercicio cumple con los parametros, no se si alguien ve algo que yo estoy viendo.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/e96f8380-4377-4042-a48d-72bc96fc2af9)

**Comment by joamza** [comment]
Quizás sea por que estas retornando una lista y se pide retornar la tupla resultante, pasa la lista a tupla y la retornas

**Comment by alejandrazapatap** [comment]
Muchas gracias😉

**Comment by joamza** [comment]
me cuentas si te funciona

**Comment by alejandrazapatap** [comment]
si, me sirvio. Muchas gracias [joamza](https://github.com/joamza) a veces se dejan pasar pequeños detalles por alto.😊
