### ISSUE TITLE
Evaluación diccionarios punto 4 - PYLVL1EDICT-04

### ISSUE THREAD

**Issue by EstebanaOrozco** [codingupmyfuture/bootcamplinuxpython#67]
El ejercicio pide:
```
Dado un parametro diccionario que entrega un objeto diccionario, escribir dentro de la función function la lógica que imprima y retorne
secuencialmente:
1. al valor de la llave email.
2. al segundo valor de la llave 'feh', tenga en cuenta que es del tipo lista
3. al valor de la llave nombre
4. tiene que tener en cuenta que alguna de las llaves solicitadas no exista en el diccionario.
```

pero el resultado de ejecución espera que uno retorne la lista completa de la llave _'feh'_  para el punto 2. En mi opinión este ejercicio está mal calificado porque se debería retonar el número 10 que es el item de la posición 2 de la lista y no la lista completa.
![Respuestas Punto 4](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/46961406/4c5e699c-2c59-45c7-9117-b019adccdbf5)

**Comment by villarrealjk** [comment]
De acuerdo contigo Estebana, me pasó igual y la solicitud del punto 2 dice claramente el segundo valor de la llave 'feh' y el bot en la calificación retorna la llave completa. Se debe corregir!!

**Comment by Cris-Cod** [comment]
Igualmente me ocurrió el dato seria 10 el segundo elemento de la lista pero el bot esta calificando sobre el total de la lista

**Comment by alejandrazapatap** [comment]
A mi me pasa igual, en el ejercicio esa es la indicacion que se da, pero el bot lo toma como la lista completa
![Captura de pantalla 2023-08-28 150703](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/ee3ac730-28a4-413e-870c-b1d15c8c3cfe)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/4301f4b4-6d38-4f43-997d-78ee43d92dba)

**Comment by Andmontc** [comment]
Hola, Buen día, es correcto, el ejercicio debe retornar el valor, ya se encuentra corregido para que envíen de nuevo el trabajo y se califique bien.

Muchas Gracias

**Comment by codingupmyfuture** [comment]
El taller fue actualizado tanto a nivel de descripción como de validaciones, por favor descárguenlo y trabajen con él.

mensaje: https://t.me/c/1786701113/919/1704
