### ISSUE TITLE
Taller #1- Pregunta #3

### ISSUE THREAD

**Issue by juliansernave** [codingupmyfuture/bootcamplinuxpython#68]
Buenas tardes Luis, tengo una duda ya que el control me calificó como mala mi respuesta:

- El primer punto solicitado es: String hasta la posicion 5. Según las clases y lo que pude averiguar en internet, posición e index es lo mismo. Razón por la cual considero que posición 5 incluye los index del 0 al 5 
- Es diferente a si solicitara hasta el elemento 5 (en ese caso sería hasta el index 4)
- Me corriges por favor si lo que digo no es correcto. Muchas gracias 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/143293003/bf39eace-4fdc-40ec-a0b6-80478e2c43fe)

En este ejemplo la palabra "Estoy" tiene 4 posiciones empezando desde cero, con 5 elementos 

Mi respuesta: "Estoy "
El Control: "Estoy"

**Comment by Giov009** [comment]
Saludos @juliansernave,

El ejercicio #3 pedía **"String hasta la posicion 5"**, recuerda que en el corchete el lado derecho siempre es un intervalo abierto, por tal motivo tomará un digito por debajo del que tú especifiques:
 Código correcto:
 **string[:5]** = 'Estoy'
Tu repuesta imprimió un espacio adicional:
**string[:6]** = 'Estoy '

**Comment by juliansernave** [comment]
Saludos @Giov009 y gracias por tu respuesta!

Estoy de acuerdo con tu respuesta, justo a eso me refiero, como es un intervalo abierto, debía colocar [:6] para que tomara el string hasta la posición 5 (osea una menos)

Con tu ejemplo, el string sólo está yendo hasta la posición 4 del elemento.... string[:5] = 'Estoy' 

E(0) S(1) T(2) O(3) Y(4) 

Para mi posición es lo mismo que índice según las clases y lo que pude averiguar en internet. Puede que ahí tenga la confusión pero no estoy seguro. Saludos!

**Comment by juliansernave** [comment]
Muchas gracias @luisvasv-teck  por tu respuesta, por favor revisa mi comentario anterior en donde pongo los dos ejemplos 
En el ejemplo de @Giov009 , no se incluye el espacio por lo cual, solo coge hasta el caracter 4. 

Como yo lo realicé incluyó el espacio, lo cual  me da un total de 5 caracteres como lo enuncia el problema 

Igualmente, yo realicé el cambio a como el bot lo calificaba para no obtener una mala nota
