### ISSUE TITLE
Error al calificar taller 1

### ISSUE THREAD

**Issue by jonathino** [codingupmyfuture/bootcamplinuxpython#69]
Buenos dias

El dia de ayer cargue el taller 1 con los codigos tal cual son solicitados.
pero al recibir la calificacion recibo 0, y no encuentro mi codigo del notebook

anexo imagen con el nombre del notebook y la solucion
y la respuesta que entrega en boot en donde no encuentra ningun codigo.
No he modificado el nombre del notebook

Muchas gracias por la ayuda.
<img width="1429" alt="resultado" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/408584/dddae79a-34fa-4e10-8528-ff5b6df5b318">
<img width="1323" alt="SCR-20230827-iofa" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/408584/09f2702a-af20-4025-97f1-4d6add72289c">

**Comment by JoseJulianMosqueraFuli** [comment]
Me parece que tienes mal la identación, 

<img width="506" alt="1" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/997242c5-290f-4514-b4f0-a1db181fa4a6">

Si lo ajustas a hasta donde te indica colab llegar, me parece que no deberías tener inconveniente.
Espero te sea de ayuda.
Si tienes más información del error, sería util.

**Comment by luisvasv-teck** [comment]
@jonathino recuerda no publicar tu código, adicionalmente recuerda lo que vimos la primera sesión, Python es un lenguaje tabular. Como lo indica @JoseJulianMosqueraFuli, por favor organiza la tabulación y vuelve a intentarlo
