### ISSUE TITLE
Dudas Taller # 1 Ejercicios 6, 7, 8, 9

### ISSUE THREAD

**Issue by bmartinez1987** [codingupmyfuture/bootcamplinuxpython#70]
Buenas tardes,
Me resultan esta calificación de taller # 1, ya se me acabaron las posibilidades, se| me ha dificultado bastante, ya que, por primera vez incursiono en el tema de programación, pero si por favor, ¿alguien puede darme una mano se lo agradecería mucho?. 

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141855974/89251b10-bba6-4743-97c5-405d026572a3)

**Comment by JoseJulianMosqueraFuli** [comment]
¿Puedes facilitar tu archivo?

**Comment by bmartinez1987** [comment]
Buenas tardes Jose Julian,
Claro que sí, muchas gracias por tu ayuda.

Buen día, quedo atento.

**Comment by bmartinez1987** [comment]
¿Si se puede, voy a enviar fotos y me cuenta por favor si puedo enviarle el archivo a algún correo.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141855974/932e1f9f-a0f0-46a3-bc0e-b9d9493e970c)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141855974/ec5a00d1-3bd1-4217-9ae6-cf39e6ad1be9)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141855974/c9d56eed-4ec3-4236-8f1a-a47b909620bc)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141855974/67c6cef3-5355-47e3-a45c-4c7f632d1a69)

Muchas gracias.

**Comment by JoseJulianMosqueraFuli** [comment]
###  1. Un error que veo general, es en la identación tienes un tab o 4 espacios de más.
#### Colab te marca las lineas de guia.
Procura que se vea así, las `|` solo son de ejemplo no debes escribirlas.
```code
def function():
|    algo
|    return algo 
```
En lugar de:
```code
def function():
|    |   algo
|    |   return algo 
```

### 2. Voy más especifico en cada en el #6 solo tienes error de identación, parece.
En el #7 se te solicita retornar más valores `return resultados_solicitados` ejemplo `return a,b,c, ...etc`, aquí van los resultados individuales que ya obtuviste, no todo en uno.
En el #8 lo mismo tienes que retornar varios resultados `return a,b,c, ...etc`
En el #9 Revisa bien lo que se te está solicitando, 
### NOTA:
- No te olvides de revisar la identación
- Cada pdf que envia el bot tiene más detalles de lo que esperaba el punto, puedes revisarlo.

Espero te sea de utilidad.

**Comment by luisvasv-teck** [comment]
Gracias por el soporte, pero recordemos tratar no de poner el código con las soluciones.
