### ISSUE TITLE
Errores taller #5 Diccionarios

### ISSUE THREAD

**Issue by LeoCometa** [codingupmyfuture/bootcamplinuxpython#71]
### **Primer error:**
Dado el siguiente enunciado en donde se pide que se modifique el valor de la edad a 30 y que se imprima y retorne el diccionario con las **modificaciones** realizadas 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/102877283/c2335c89-4f46-4606-9bff-3f2e0dd04bad)
El control da como resultado correcto la edad sin la modificación, también estaría bien que en el enunciado explicaran o dijeran que el celular había que tomarlo como un **str** y no como un **int**  
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/102877283/15b10c27-86dd-4d4d-af3e-f2dc702c7e06)

### **Segundo error:**
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/102877283/1bf1e271-ab3c-4bac-80c9-6739bd277bc5)
Dentro de la función no hay ningún diccionario 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/102877283/2e4bf2f5-75b6-4f0f-b327-c941a80eaf4d)
Aún así el control da una respuesta con un diccionario que en el ejercicio no se nos está dando.

**Comment by melenabelt** [comment]
El error del ejercicio 05 es que en el enunciado no nos brinda el diccionario exacto que está pidiendo la máquina y además, el enunciado nos dice que eliminemos el de preferencia, pero la realidad es que deben ser exactamente nombre e email.

<img width="554" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/58674385/63d6227b-48c1-40bb-85a4-a4368d427f13">

Si no eliminas esos dos sino el que quieras, te va a generar error. Así que, para poder pasar ese punto, sí o sí debes perderlo al menos 1 o 2 veces:

1. Para copiar exactamente el diccionario que envía la máquina
2. Para entender que deben eliminarse esas dos llaves en específico

**Comment by JoseJulianMosqueraFuli** [comment]
El primero es un error en la guía, como ya te diste cuenta el valor correcto es 25.
El Segundo, veo que tienes mal identado los valores dentro de la función además parece que te esta marcando un error en `function`, en la respuesta se muestra el diccionario que espera, te puedes guiar de el.
```code 
original = {
'nombre': 'nombre',
'dirección': 'direccion',
'teléfono': 'telefono',
'email': 'email',
'preferente': 'S'
}.
```
