### ISSUE TITLE
Error en el ejercicio #3 de Diccionarios

### ISSUE THREAD

**Issue by alejandrazapatap** [codingupmyfuture/bootcamplinuxpython#72]
En el ejercicio te pide agregar el celular donde el valor es numerico, pero cuando el bot te califica lo retorna como string?
![Captura de pantalla 2023-08-28 174453](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/54c4415e-e2e1-4420-816f-6de42d2abd8d)
![Captura de pantalla 2023-08-28 174633](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/97615442/1d324e6b-6741-4959-a555-ff66bac0027d)

**Comment by luisvasv-teck** [comment]
Revisando el enunciado, en ninguna parte se indica que debe ser numérico ni tampoco texto. Pero normalmente los números de teléfono se manejan como tipo `str`, ya que si se tuviera que agregar números de otros países, algunos indicativos como el 0 adelante, al ser números, se eliminarían o `+573...` por lo cual puede ser una forma de entendimiento, pero no significa que sea un error puntualmente.

Para más info:

https://www.cuandoenelmundo.com/herramientas/codigos-para-llamadas-internacionales

**Comment by isamorren** [comment]
Adicional en este mismo problema, Si ya se mutó la edad a 30 por qué el resultado del control sigue siendo 25 teniendo en cuenta que pide Imprimir y retornar el diccionario con las modificaciones realizadas? 
Les agradezco la aclaración.
