### ISSUE TITLE
Calificación taller 3

### ISSUE THREAD

**Issue by Danitcas** [codingupmyfuture/bootcamplinuxpython#73]
El ejercicio número 5 me sale calificado como malo, sin embargo en la retroalimentación dice superado y tengo la misma respuesta que debería dar, veo que el bot lo compara con (-1) pero esa salida corresponde a una entrada diferente, adjunto imagen, no sé que pasa.
![Uploading IMG_20230828_174648.jpg…]()
Muchas gracias 😊

**Comment by Laurisvilla** [comment]
Hola, me paso lo mismo

**Comment by Danitcas** [comment]
Y con el primer punto también me pasa igual, me sale superado pero calificado como malo, entonces no se que salió mal 💔

**Comment by Danitcas** [comment]
Claro, el ejercicio 5 me sale calificado como "failed", Debido a:
La solución no superó la prueba: Respuesta estudiante (19,) != respuesta control: (-1,), sin embargo no entiendo porque la respuesta control sería (-1), cuando esa respuesta corresponde a una entrada diferente a la que tengo, es decir, mi entrada pide que obtenga la primer ocurrencia de 'abc' y es 19, la entrada a la que corresponde el (-1) es a la 'zjf' según la retroalimentación del bot. Creo que hay un error porque incluso el bot en la tabla nombrada "ESTUDIANTE" coloca mi respuesta como superado, pero la calificación esta como malo.
Intentaré añadir otras imágenes:

![captura 1](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141188134/e2950826-e85d-4d59-8152-9597a3c33b9d)
![captura 2](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141188134/7a67827a-81f1-46e1-9884-268367411e7c)

**Comment by JoseJulianMosqueraFuli** [comment]
El bot marca superado las respuestas que el tiene de control, al evaluar tu código únicamente tienes correcto el primer valor, los demás fallan.
Por lo que veo se mantiene fijado el 19, deberías revisar tu código porque como se dijo las respuestas de control pueden variar las entradas de la función.

**Comment by Danitcas** [comment]
Muchas gracias, a que te refieres cuando dices que los demás fallan?, no entiendo que más debo hacer :( pensé que solo me pedían la primer ocurrencia de 'abc'

![captura 3](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141188134/358c55ff-468a-4398-87b7-566f69812a39)

**Comment by JoseJulianMosqueraFuli** [comment]
Fallan por qué el código no solo busca 'abc' busca diferentes valores que la función llama en el valor string.
En lugar de buscar 'abc' deberías buscar el valor string 
```code
def function(lista, string)
    Busca string en lugar de 'abc'
```

**Comment by Danitcas** [comment]
Entiendo 😊 muchas gracias, voy a corregirlo

**Comment by JoseJulianMosqueraFuli** [comment]
Con gusto @Danitcasz, nos cuentas cómo te va.
Por otro lado @Laurisvilla, ¿tienes alguna duda adicional?

**Comment by CristianMongar** [comment]
Hola compañer@s. 

Algun@ pudo resolver el tema del -1 que se espera en la ultima prueba de control del punto 5 del taller 3? 
![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/11049906/64b8e460-57b7-45f8-873a-d52debeadf1c)

Se supone que cuando se le pasa el segundo parámetro ("zjf") a la función debería de entregar como respuesta el error: ValueError: substring not found, pero en el control del bot la respuesta es -1.

**Comment by JoseJulianMosqueraFuli** [comment]
Se más a una convención, al no encontrarse el valor se retorna `-1`
