### ISSUE TITLE
Taller 5 - Pregunta 3

### ISSUE THREAD

**Issue by mariafrancodev** [codingupmyfuture/bootcamplinuxpython#75]
#67 En el ejercicio planteado piden modificar el valor del diccionario de la edad a 30, pero la califica como malo.

<img width="756" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/42823670/12fcedb9-1431-4f1a-8ac6-e0133dea71ff">

**Comment by Danitcas** [comment]
Hola, me pasa lo mismo

**Comment by Jemmay7** [comment]
chicos el numero de telefono debe ser un string
