### ISSUE TITLE
Taller 6 - Aclaración punto 2

### ISSUE THREAD

**Issue by mariafrancodev** [codingupmyfuture/bootcamplinuxpython#76]
En el punto 2 nos piden lo siguiente: Dado los siguientes sets `set1= {1, 2, 3, 4, 5}` y `set2= {4, 5, 6, 7, 8} `Escribir dentro de la función function la lógica para aplicar dos formas diferentes para obtener e imprimir la diferencia entre **ambos sets**.

Yo puse la diferencia de **ambos sets**, pero el bot califica la diferencia del **set1** contra el **set2**. Sería bueno aclarar esto, ya que la diferencia de ambos sets sería con `.symmetric_difference()` Pero del set1 contra el set2 si sería con `.difference()` o así lo entendí yo. 

Gracias :)

<img width="753" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/42823670/7f73576c-c997-42d7-aa4e-7848e9f90fef">

**Comment by Cris-Cod** [comment]
Hola si deberias usar el  metodo difference() el cual busca la diferencia entre los dos sets, el cual se puede realizar la diferencia entre X contra Y   y   Y contra X

**Comment by JoseJulianMosqueraFuli** [comment]
Con el `.symmetric_difference()` obtenemos todos los valores eso esta perfecto, por que obtienes los valores de diferencia, más la respuesta esperada espera dos elementos `print/return elementos_diferentes_operacion_1, elementos_diferentes_operacion_2`
Creo que en la longitud de los resultados está la solución a tu problema, puedes partir el resultado así, `{1, 2, 3}, {6, 7, 8}`
O usar la diferencia entre ambos.
