### ISSUE TITLE
Cual es mi error ejercicio numero 4 taller 1

### ISSUE THREAD

**Issue by uancamilo** [codingupmyfuture/bootcamplinuxpython#78]
```
def function(__unused):
    """Escriba su codigo aqui...""";
    palabra1 = "Estoy";
    palabra2 = "aprendiendo";
    palabra3 = "python";


    resultado = palabra1 + " " + palabra2 + " " + palabra3;

    return resultado

function(None)

**Comment by keljozap** [comment]
Hola compañero buenas tardes. El ejercicio dice concatene las variables, las 3 que te piden crear. Para que creas una 4ta variable? Entiendo que es para concatenar las 3 anteriores, pero el ejercicio no esta hablando de crear una 4ta variable y de hecho te esta pidiendo que retornes la concatenación de las 3 variables creadas. Te lo esta marcando malo porque el bot está esperando las 3 variables que creaste, y no una.

**Comment by uancamilo** [comment]
ya intente de esa forma en una vez anterior. 
![Screenshot from 2023-08-31 12-53-46](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/36907625/817eacf2-3747-4844-ac91-8d84bcc7e793)

**Comment by keljozap** [comment]
Compañero, el código que adjuntas no es lo mismo que te estoy indicando yo, estas agregando una variable para un espacio, para qué? El ejercicio esta indicando que sean 3 variables con 3 palabras. Y tu estas adjuntando 1 espacio y dos palabras, por eso te lo esta marcando malo.

**Comment by luisvasv-teck** [comment]
Si miras detenidamente el ejercicio y la respuesta del bot, te está diciendo que la solución espera solo la creación de 3 variables únicamente: 

<img width="1127" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/108821097/437a1c2a-b5db-42d2-ad1d-b072f22da0b5">

pero en la solución que posteas hay 4:
```
palabra1 = "Estoy";                                                             # variable # 1
palabra2 = "aprendiendo";                                                # variable # 2
palabra3 = "python";                                                          # variable # 3
resultado = palabra1 + " " + palabra2 + " " + palabra3;  # variable # 4

```

Adicionalmente, se recomienda mirar este [notebook de la sesión 1](https://github.com/codingupmyfuture/bootcamplinuxpython/blob/main/contenido.curso/003.notebooks/LVL-1/LVL1.01.intro.ipynb), ya que Python es un lenguaje tabular, y no requiere ` ;` para confirmar cada línea escrita

**Comment by edallanpoe** [comment]
Como expresa la compañera Kelly, el concepto a emplear detrás de cada uno de los ejercicios, sí se ha enseñado en las clases, sin mencionar la documentación inicial que cada uno de los notebook contiene en la primera celda. Sobre todo el propósito de este bootcamp no es solo enseñar al estudiantado como utilizar y aplicar un lenguaje de programación, sino también alentarlos a ir mas allá del conocimiento impartido y buscar de manera autodidacta el enfoque más óptimo para llegar a la solución deseada, tan necesario en la vida profesional.

Adicionalmente, con respecto al reporte de calificación enviado en respuesta a los ejercicios, se entrega una conclusión explicando la razón de la calificación y también se entregan las respuestas de control para ser tomadas como referencia a la hora de hacer los cambios pertinentes antes enviar un nuevo intento.

Sería poco ético de nuestra parte entregar la solución del ejercicio.

Entiendo la frustración de no lograr la respuesta correcta, sin embargo, despues de revisado el ejercicio, es posible confirmar que el enunciado es claro y es congruente con las respuestas del control. Ahora, sí se encuentra un posible error en la lógica del ejercicio, agradecemos generar un nuevo issue donde de manera argumentativa y reproducible se explique el error y su causa, en dado caso, realizaremos las correcciones pertinentes.

*Recuerda que, estamos abiertos a criticas constructivas que aporten valor al curso y enaltecemos las contribuciones que los mismos miembros (Estudiantes) de la comunidad hacen. Mejor ejemplo a como funciona el mundo real, imposible.

Dicho esto, lamentamos que la forma de calificación no cumpla con las expectativas de algunos estudiantes, sin embargo, si tienen una mejor solución agradeceríamos, o mejor dicho, los exhortamos a entregarnos dicha solución con la que colaborativamente construyamos una herramienta que sea mas enriquecedora y de mayor valor hacia ustedes.

Sin mas que decir,

Muchas gracias por tu aporte y activa participación, y mucha suerte en los proximos ejercicios.

¡¡Happy Coding!!
