### ISSUE TITLE
Calificación de taller #4 Diccionarios punto 1

### ISSUE THREAD

**Issue by pradadeveloper** [codingupmyfuture/bootcamplinuxpython#82]
Hola buenas tardes, 
Tengo una duda. En el taller #4 estoy teniendo problemas al momento en que me califican. Me están poniendo que el punto está malo porque hubo "Error en ejecución" y me dan este argumento, es como si el código no corriera, pero a mi si me corre en colab e inclusive me saca la misma respuesta que CONTROL.

Ejercicio no superado. Puntuación obtenida: 0.0% Puntuación mínima requerida: 75.0%
Debido a: El ejercicio falló su ejecución debido a: Traceback (most recent call last): File
"/Users/lvasq/repositories/personal/evaluator/evaluator/src/qualifier/exercise.py", line 284, in
_run_exercise asserts(v, result, control) File "<string>", line

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/96214131/26691255-dc19-432e-a094-087668989a3c)

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/96214131/5564371f-b166-41e1-bdd6-5bb6db7cdfd8)

**Comment by andresarad1** [comment]
Te recomendaría que en el return envíes los dos diccionarios, el diccionario_null y diccionario, a mi me sacaba un error parecido y era por esta razón

**Comment by keljozap** [comment]
Hola @pradadeveloper buenas tardes. Efectivamente lo que indica @andresarad1 y el control que adjuntas es que debes retornar ambos diccionarios, primero el vacio y luego el resultante.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/3f2f4406-4dca-47cd-858a-1a850c1a15e1)

Igualmente adjunto las notas del ejercicio donde se indica que se retornen ambos.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/f8dd7972-d0a5-4cf8-a623-ad52269a5716)

Gracias a @andresarad1 por la respuesta.

Feliz tarde!
