### ISSUE TITLE
taller 5 punto 3

### ISSUE THREAD

**Issue by hrriverar** [codingupmyfuture/bootcamplinuxpython#85]
En mi respuesta dice que uno de los valores no es el esperado, quisiera saber si el número de telefono se lo deja como número o es str?
Veo que lo unico diferente es el parentesis del número.
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/134157669/1ac77a85-1b9d-4d53-9e5a-76c17fb1840e)

**Comment by JoseJulianMosqueraFuli** [comment]
El numero celular lo dejas como string.

**Comment by hrriverar** [comment]
Muchas gracias
