### ISSUE TITLE
Calificación punto 2, taller de listas, tengo todo idéntico.

### ISSUE THREAD

**Issue by CrisGos** [codingupmyfuture/bootcamplinuxpython#86]
Buenos días,

Presento un problema con la calificación del punto 2 del taller de listas, según mi respuesta y la respuesta de control debería estar correcto, ya revisé las reglas y las he seguido también.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141366914/a264a17e-f587-49af-ad7e-42637b427d18)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/141366914/779699ae-5f3a-4604-98b6-ab8c89997807)

**Comment by JoseJulianMosqueraFuli** [comment]
Aunque paresca que tienes los mismo valores estas obteniedo un resultado diferente `[[ ]]` tienes la lista resultado, contenida en otra lista,  así deberia ser tu respuesta`[ ]` , espero te haya sido de ayuda.

**Comment by CrisGos** [comment]
> Aunque paresca que tienes los mismo valores estas obteniedo un resultado diferente `[[ ]]` tienes la lista resultado, contenida en otra lista, así deberia ser tu respuesta`[ ]` , espero te haya sido de ayuda. Revisa la lista que retornas no este contenida en otra: `[[15, 14, 13, 12, 11, 10, 9, 8, ...]]` a `[15, 14, 13, 12, 11, 10, 9, 8,...]`

Sí, tienes razón, muchas gracias!!
