### ISSUE TITLE
Error en la última respuesta del control de bot en el ejercicio 5 del tallar 3 de listas. 

### ISSUE THREAD

**Issue by CristianMongar** [codingupmyfuture/bootcamplinuxpython#87]
Hola compañer@s.

Algun@ pudo resolver el tema del -1 que se espera en la ultima prueba de control del punto 5 del taller 3?

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/11049906/e1da1dcf-a4b5-4f7f-b8d1-232d840ebf76)

Se supone que cuando se le pasa el segundo parámetro ("zjf") a la función debería de entregar como respuesta el error: ValueError: substring not found, pero en el control del bot la respuesta es -1.

**Comment by JoseJulianMosqueraFuli** [comment]
https://github.com/codingupmyfuture/bootcamplinuxpython/issues/73#issuecomment-1704354600

**Comment by SBuriticaM** [comment]
Hola, eso depende del método que usas:
.index(variable a buscar): retorna el índice de la posición donde encuentra el primer carácter donde inicia la ocurrencia y si no lo encuentra da como resultado error de ejecución.
.find(variable a buscar): retorna el índice de la posición donde encuentra el primer carácter donde inicia la ocurrencia y si no lo encuentra da como resultado -1.
Quizás hayan más diferencias, pero así se puede solucionar.

**Comment by CristianMongar** [comment]
Era eso lo que pasaba. Muchas Gracias por la info @SBuriticaM.
