### ISSUE TITLE
Problema en la formulacion de la pregunta PYLVL2CCOND-02

### ISSUE THREAD

**Issue by jaca131** [codingupmyfuture/bootcamplinuxpython#91]
en las condiciones que nos piden evaluar son estos 

1. Si el dueño del carnet tiene menos de 100 puntos realizaremos un descuento del 10%.
2. Si el dueño del carnet tiene un número de puntos que sea mayor o igual a 100 y menor o igual a 150 aplicamos un descuento del 12%.
3. Si el dueño del carnet tiene un número de puntos igual a 150 haremos un descuento de 15%.
4. Sino, para el resto de los casos de más de 150, un descuento de 20%.

Si dejamos como esta el punto  2. en la parte que dice menor o igual usaríamos este símbolo "<=" entonces nunca nos evaluaría la siguiente condición para dar el 15 % que es si los puntos son igual a 150 ya que esta condición esta implícita en la parte dos de nuestro codigo

**Comment by Lera2597** [comment]
Estoy de acuerdo con @jaca131 . si el valor es exactamente 150 nunca se cumplira el paso 3.

**Comment by andresarad1** [comment]
El punto 3 se cumplirá cuando sea 150 exactamente, ya que el tomara la primer condición que se cumpla, aunque se cumplan dos la de  igual a 150 y las del resto pero al ser el igual a 150 el primero tomara este y ya obviara los otros (el otro)

**Comment by ChristYela** [comment]
al hacer una prueba de escritorio: si se considera el segundo punto de " 100 <= puntos < = 150 ", toma el " 12% ", pero si se toma el tercer punto de " puntos == 150 ", que debería tomar el " 15% ",  toma realmente el " 12 % " ; para que se cumpla el segundo punto, debería ser " 100 <= puntos <  150 ", para que en el  tercer punto de " puntos == 150 ", realmente tome el " 15% "

**Comment by CristianMongar** [comment]
Ando con la misma duda.

**Comment by JoseJulianMosqueraFuli** [comment]
Tengo la misma duda, Nos pueden aclarar @codingupmyfuture o @luisvasv-teck, ¿que valor tomar cuando sea exactamente igua al 150?

- Si el dueño del carnet tiene un número de puntos que sea mayor o igual a 100 y **MENOR O IGUAL** a 150 aplicamos un descuento del 12%.
- Si el dueño del carnet tiene un número de puntos **IGUAL** a 150 haremos un descuento de 15%.

**Comment by ChristYela** [comment]
Lo expliqué hace unos días, algún posible error de redacción, algo similar pasa con otro ejercicio de este nivel, ver el otro issue que se detalla al respecto. Antes de enviar trabajo alguno, es recomendable hacer las debidas pruebas de escritorio, y validar con distintos valores si logran cumplirse las diferentes condiciones según el ejercicio. Feliz fin de semana.

**Comment by maurorpo** [comment]
Lo entiendo de la siguente manera:

- Punto 2: la condicion valida ambas cosas: tiene un número de puntos que sea mayor o igual a 100 y menor o igual a 150. tener presente que menciona que sea mayor o igual a 100 **Y** menor o igual a 150

-Punto 3: La condición solo es una: número de puntos igual a 150

En resumen, en el punto 2 se deben de cumplir ambas cosas, en el punto 3 solo una

**Comment by ChristYela** [comment]
> Lo entiendo de la siguente manera:
> 
> * Punto 2: la condicion valida ambas cosas: tiene un número de puntos que sea mayor o igual a 100 y menor o igual a 150. tener presente que menciona que sea mayor o igual a 100 **Y** menor o igual a 150
> * Punto 3: La condición solo es una: número de puntos igual a 150
> 
> En resumen, en el punto 2 se deben de cumplir ambas cosas, en el punto 3 solo una

PERO con ese supuesto así planteado "originalmente". al cumplirse ambos valores de 150, así en el tercer caso el descuento es del 15%, tomará el del 12% en ambos casos.  

Así lo argumenté hace unos días: Si hacemos una prueba de escritorio: si se considera el segundo punto de " 100 <= puntos < = 150 ", toma el " 12% ", pero si se toma el tercer punto de " puntos == 150 ", que debería tomar el " 15% ", toma realmente el " 12 % " ; para que se cumpla el segundo punto, debería ser " 100 <= puntos < 150 ", para que en el tercer punto de " puntos == 150 ", realmente tome el " 15% "

**Comment by maurorpo** [comment]
No se si sea válido, pero si coloco la condición 3 antes de la 2, le daría prioridad a esa condición.

**Comment by maurorpo** [comment]
Encontré algo:
Nota: solo se ejecutará la primera condición que se evalúe como true. Esto significa que un else solo se ejecutará si ninguna de las condiciones es true.

**Comment by ChristYela** [comment]
> No se si sea válido, pero si coloco la condición 3 antes de la 2, le daría prioridad a esa condición.

PERO no tendría sentido alguno cuando un valor sea menor o  igual a 150 (contando el 150), en el segundo caso aplique el 12% y luego en el tercer caso que textualmente es igual a 150, en teoría tendría que aplicar el 15%, pero si se toma el texto original. tomaría el 12% en vez del 15% cuando se hace la prueba de escritorio con el 150.

**Comment by maurorpo** [comment]
> > No se si sea válido, pero si coloco la condición 3 antes de la 2, le daría prioridad a esa condición.
> 
> PERO no tendría sentido alguno cuando un valor sea menor o igual a 150 (contando el 150), en el segundo caso aplique el 12% y luego en el tercer caso que textualmente es igual a 150, en teoría tendría que aplicar el 15%, pero si se toma el texto original. tomaría el 12% en vez del 15% cuando se hace la prueba de escritorio con el 150.

Entiendo, creo que esto solucionaría la parte técnica, sobre el problema ya tocaría esperar que nos aclaren

**Comment by ChristYela** [comment]
> > > No se si sea válido, pero si coloco la condición 3 antes de la 2, le daría prioridad a esa condición.
> > 
> > 
> > PERO no tendría sentido alguno cuando un valor sea menor o igual a 150 (contando el 150), en el segundo caso aplique el 12% y luego en el tercer caso que textualmente es igual a 150, en teoría tendría que aplicar el 15%, pero si se toma el texto original. tomaría el 12% en vez del 15% cuando se hace la prueba de escritorio con el 150.
> 
> Entiendo, creo que esto solucionaría la parte técnica, sobre el problema ya tocaría esperar que nos aclaren

Estuvo bueno el debate. ah y en el otro issue pasa algo parecido, no se si ya le has dado un vistazo y feliz finde.

**Comment by Elioric** [comment]
Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:

si ...
# condiciones anteriores
si 100 <= puntos <= 150:
    hacer descuento = 12
    si puntos = 150:
        hacer descuento = 15
si ...
# condiciones posteriores

**Comment by juli-amezquita** [comment]
> Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> 
> ```
> si ...
> # condiciones anteriores
> si 100 <= puntos <= 150:
>     hacer descuento = 12
>     si puntos = 150:
>         hacer descuento = 15
> si ...
> # condiciones posteriores
> ```

¡Hola! yo también estaba pensando en el tema y creo que la forma en como lo aborda @Elioric es adecuada. Viéndolo de esa manera (como un condicional anidado), lo que se estaría diciendo es: _"si la cantidad de puntos está en el rango de 100 a 150 (inclusive), se aplica un descuento del 12%, pero si la cantidad de puntos es exactamente igual a 150, se hace un descuento del 15%"_
 
Yo ya lo probé como dice @Elioric y funciona, no lo había visto de esta manera pero creo que sería una buena lógica para abordarlo. ¡Gracias!

**Comment by ChristYela** [comment]
> > Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> > ```
> > si ...
> > # condiciones anteriores
> > si 100 <= puntos <= 150:
> >     hacer descuento = 12
> >     si puntos = 150:
> >         hacer descuento = 15
> > si ...
> > # condiciones posteriores
> > ```
> 
> ¡Hola! yo también estaba pensando en el tema y creo que la forma en como lo aborda @Elioric es adecuada. Viéndolo de esa manera (como un condicional anidado), lo que se estaría diciendo es: _"si la cantidad de puntos está en el rango de 100 a 150 (inclusive), se aplica un descuento del 12%. Sin embargo, si la cantidad de puntos es exactamente igual a 150, se hace un descuento del 15%"_
> 
> Yo ya lo probé como dice @Elioric y funciona, no lo había visto de esta manera pero creo que sería una buena lógica para abordarlo. ¡Gracias!

Bueno, también hice esa prueba de esa forma, y si los puntos son == a 150, el porcentaje sería el 15%, y no habría ese conflicto con el porcentaje de 12% ( 100 <= puntos <= 150, tomando como valor máximo de prueba de 149 para que cumpla con el 12%), ya que con 150 exactos se cumpliría con el 15% . estuvo muy bueno el debate con ese detalle. para llegar al resultado esperado. Gracias tanto a las compañeras como a los compañeros con sus aportes.

**Comment by maurorpo** [comment]
> Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> 
> ```
> si ...
> # condiciones anteriores
> si 100 <= puntos <= 150:
>     hacer descuento = 12
>     si puntos = 150:
>         hacer descuento = 15
> si ...
> # condiciones posteriores
> ```

Genial tu respuesta, no lo había pensado. Como comentario creo que la validación tiene un error, debe de ser:
si 100 >= puntos <= 150

**Comment by ChristYela** [comment]
> > Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> > ```
> > si ...
> > # condiciones anteriores
> > si 100 <= puntos <= 150:
> >     hacer descuento = 12
> >     si puntos = 150:
> >         hacer descuento = 15
> > si ...
> > # condiciones posteriores
> > ```
> 
> Genial tu respuesta, no lo había pensado. Como comentario creo que la validación tiene un error. Debe de ser: `si 100 >= puntos <= 150`
> 
> y lo tienes: `si 100 <= puntos <= 150`

Está bien escrito de la forma "original":  100 <= puntos <= 150: ; se lee la primera "mitad" de derecha a izquierda  y luego la segunda "mitad" se lee de izquierda a derecha : 

el planteamiento de la compañera:  100 <= puntos <= 150
100 <= puntos | El número de puntos es mayor o igual a 100.
puntos <= 150 | El número de puntos es menor o igual a 150.

su contrapropuesta: 100 >= puntos <= 150
100 >= puntos | El número de puntos es menor o igual a 100.
puntos <= 150 | El número de puntos es menor o igual a 150.

Serían dos expresiones diferentes.

**Comment by maurorpo** [comment]
> > > Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> > > ```
> > > si ...
> > > # condiciones anteriores
> > > si 100 <= puntos <= 150:
> > >     hacer descuento = 12
> > >     si puntos = 150:
> > >         hacer descuento = 15
> > > si ...
> > > # condiciones posteriores
> > > ```
> > 
> > 
> > Genial tu respuesta, no lo había pensado. Como comentario creo que la validación tiene un error. Debe de ser: `si 100 >= puntos <= 150`
> > y lo tienes: `si 100 <= puntos <= 150`
> 
> Está bien escrito de la forma "original": 100 <= puntos <= 150: ; se lee la primera "mitad" de derecha a izquierda y luego la segunda "mitad" se lee de izquierda a derecha :
> 
> el planteamiento de la compañera: 100 <= puntos <= 150 100 <= puntos | El número de puntos es mayor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> 
> su contrapropuesta: 100 >= puntos <= 150 100 >= puntos | El número de puntos es menor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> 
> Serían dos expresiones diferentes.

100 <= puntos | El número de puntos es mayor o igual a 100.
En esta linea no se valida mayor, ahí estas validando menor o igual a 100
el signo de mayor es >

**Comment by ChristYela** [comment]
> > > > Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> > > > ```
> > > > si ...
> > > > # condiciones anteriores
> > > > si 100 <= puntos <= 150:
> > > >     hacer descuento = 12
> > > >     si puntos = 150:
> > > >         hacer descuento = 15
> > > > si ...
> > > > # condiciones posteriores
> > > > ```
> > > 
> > > 
> > > Genial tu respuesta, no lo había pensado. Como comentario creo que la validación tiene un error. Debe de ser: `si 100 >= puntos <= 150`
> > > y lo tienes: `si 100 <= puntos <= 150`
> > 
> > 
> > Está bien escrito de la forma "original": 100 <= puntos <= 150: ; se lee la primera "mitad" de derecha a izquierda y luego la segunda "mitad" se lee de izquierda a derecha :
> > el planteamiento de la compañera: 100 <= puntos <= 150 100 <= puntos | El número de puntos es mayor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> > su contrapropuesta: 100 >= puntos <= 150 100 >= puntos | El número de puntos es menor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> > Serían dos expresiones diferentes.
> 
> 100 <= puntos | El número de puntos es mayor o igual a 100. En esta linea que pusiste no estás validando mayor o igual, ahí estas validando menor o igual a 100 el signo de mayor es >
> 
> o estoy algo confundido 😅

***se lee la primera "mitad" de derecha a izquierda y luego la segunda "mitad" se lee de izquierda a derecha*** :
"100 <= puntos <= 150: "
100 <= puntos | El número de puntos es mayor o igual a 100. **( se lee de izquierda a derecha) es igual que escribir esto:
puntos >= 100 | El número de puntos es mayor o igual a 100. ** (se lee de derecha a izquierda)
puntos <= 150 | El número de puntos es menor o igual a 150.

usted había escrito
"100 >= puntos <= 150"
100 >= puntos | El número de puntos es menor o igual a 100 **( se lee de izquierda a derecha) es diferente  que escribir esto:
puntos >= 100 | El número de puntos es mayor o igual a 100.
puntos <= 150 | El número de puntos es menor o igual a 150.

es completamente diferente

**Comment by juli-amezquita** [comment]
> > > > Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> > > > ```
> > > > si ...
> > > > # condiciones anteriores
> > > > si 100 <= puntos <= 150:
> > > >     hacer descuento = 12
> > > >     si puntos = 150:
> > > >         hacer descuento = 15
> > > > si ...
> > > > # condiciones posteriores
> > > > ```
> > > 
> > > 
> > > Genial tu respuesta, no lo había pensado. Como comentario creo que la validación tiene un error. Debe de ser: `si 100 >= puntos <= 150`
> > > y lo tienes: `si 100 <= puntos <= 150`
> > 
> > 
> > Está bien escrito de la forma "original": 100 <= puntos <= 150: ; se lee la primera "mitad" de derecha a izquierda y luego la segunda "mitad" se lee de izquierda a derecha :
> > el planteamiento de la compañera: 100 <= puntos <= 150 100 <= puntos | El número de puntos es mayor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> > su contrapropuesta: 100 >= puntos <= 150 100 >= puntos | El número de puntos es menor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> > Serían dos expresiones diferentes.
> 
> 100 <= puntos | El número de puntos es mayor o igual a 100. En esta linea que pusiste no estás validando mayor o igual, ahí estas validando menor o igual a 100 el signo de mayor es >
> 
> o estoy algo confundido 😅


Lo que @Elioric dice con la expresión `100 <= puntos <= 150` se lee de la siguiente manera:

**_"Si el valor de la variable `puntos` es mayor o igual a 100 y, al mismo tiempo, es menor o igual a 150"_** (se lee, tal cual siguiendo las indicaciones de @ChristYela). Lo cual es correcto, pues es lo que pide el ejercicio.

En otras palabras, con esta expresión se establece una condición compuesta que se debe cumplir si puntos tiene un valor que está dentro del rango entre 100 y 150, inclusive. 

La expresión que tu utilizaste se lee así: 

**_"puntos es menor o igual a 100 y, al mismo tiempo, es menor o igual a 150"_**

y en este caso, para evitar confusiones, la notación estándar para escribirlo sería la siguiente:  

`puntos ≤ 100 y puntos ≤ 150`

**Comment by maurorpo** [comment]
> > > > > Me uno tarde a la discusión, sin embargo, vería que también se puede plantear como condicionales anidados:
> > > > > ```
> > > > > si ...
> > > > > # condiciones anteriores
> > > > > si 100 <= puntos <= 150:
> > > > >     hacer descuento = 12
> > > > >     si puntos = 150:
> > > > >         hacer descuento = 15
> > > > > si ...
> > > > > # condiciones posteriores
> > > > > ```
> > > > 
> > > > 
> > > > Genial tu respuesta, no lo había pensado. Como comentario creo que la validación tiene un error. Debe de ser: `si 100 >= puntos <= 150`
> > > > y lo tienes: `si 100 <= puntos <= 150`
> > > 
> > > 
> > > Está bien escrito de la forma "original": 100 <= puntos <= 150: ; se lee la primera "mitad" de derecha a izquierda y luego la segunda "mitad" se lee de izquierda a derecha :
> > > el planteamiento de la compañera: 100 <= puntos <= 150 100 <= puntos | El número de puntos es mayor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> > > su contrapropuesta: 100 >= puntos <= 150 100 >= puntos | El número de puntos es menor o igual a 100. puntos <= 150 | El número de puntos es menor o igual a 150.
> > > Serían dos expresiones diferentes.
> > 
> > 
> > 100 <= puntos | El número de puntos es mayor o igual a 100. En esta linea que pusiste no estás validando mayor o igual, ahí estas validando menor o igual a 100 el signo de mayor es >
> > o estoy algo confundido 😅
> 
> Lo que @Elioric dice con la expresión `100 <= puntos <= 150` se lee de la siguiente manera:
> 
> **_"Si el valor de la variable `puntos` es mayor o igual a 100 y, al mismo tiempo, es menor o igual a 150"_** (se lee, tal cual siguiendo las indicaciones de @ChristYela). Lo cual es correcto, pues es lo que pide el ejercicio.
> 
> En otras palabras, con esta expresión se establece una condición compuesta que se debe cumplir si puntos tiene un valor que está dentro del rango entre 100 y 150, inclusive.
> 
> La expresión que tu utilizaste se lee así:
> 
> **_"puntos es menor o igual a 100 y, al mismo tiempo, es menor o igual a 150"_**
> 
> y en este caso, para evitar confusiones, la notación estándar para escribirlo sería la siguiente:
> 
> `puntos ≤ 100 y puntos ≤ 150`

Entiendo, estaba enredado con la sintaxis, gracias!
