### ISSUE TITLE
Problema con Punto 10 Taller 1 - Nivel 2

### ISSUE THREAD

**Issue by EstebanSancho** [codingupmyfuture/bootcamplinuxpython#94]
Tengo una duda respecto al último punto del taller 1. Los parámetros de entrada son un valor y un tipo, y decir si el tipo que se ingresó corresponde al mismo tipo del valor. En uno de los parametros ingrega como valor "True" y tipo "int" ... la respuesta debería ser False, ya que true es bool, no int (entiendo todo lo de que a veces true puede ser 1 y false 0, pero no es el caso)  El bot lo evalúa como si True fuera tipo Int. Será tal vez un error?
![1](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/111448556/46a81a86-1551-48a7-878f-dda12193d8fe)

**Comment by EstebanSancho** [comment]
Ya se solucionó, utilicé el método incorrecto. Por las dudas, usen isinstance

**Comment by Elioric** [comment]
Buenas tardes, @EstebanSancho. Podrías volver a abrir el issue? 

Es cierto que con isinstance los booleanos se evalúan y son equivalentes a los enteros porque representan unos y ceros. Sin embargo, haciendo comparación de los tipos type(A) == int, sí se devuelve falso porque se hace la distinción de booleanos y enteros.

Sería bueno que el equipo de Softserve nos aclare la duda ya que dice que se puede resolver de dos maneras, pero isinstance() y comparación de tipos no son equivalente según lo visto en este ejercicio.

**Comment by Elioric** [comment]
Igualmente, encontré ésta información donde lo explican https://stackoverflow.com/questions/37888620/comparing-boolean-and-int-using-isinstance#:~:text=For%20historic%20reasons%2C%20bool%20is,values%20returned%201%20or%200.

**Comment by EstebanSancho** [comment]
Hola @Elioric , no sé cómo volver a abrir el issue pero tienes razón. Déjame reviso como abrirlo de nuevo
