### ISSUE TITLE
Taller 4 (Bucles) - Pregunta 11

### ISSUE THREAD

**Issue by edcalderin** [codingupmyfuture/bootcamplinuxpython#96]
**Calcular el mínimo múltiplo junto con los factores.**

La salida del algoritmo que imaginé para este ejercicio coincide con los valores retornados para el minimo multiplo de 1 hasta N de la respuesta de control, pero no con los factores.

Ejemplos:

* n=9
La espuesta control es ```(2520, [9, 8, 7, 6, 5])```
Los factores que genera mi código e incluso haciéndolo con papel y lápiz son ```[9, 8, 7, 5]``` (sin el 6) lo cual se comprueba al multiplicarlos:

9x8x7x5 = **2520**.
Con la respuesta de control: 9x8x7x6x5 = 15120.

* n=13
Respusta de control: ```(360360, [13, 12, 11, 10, 9, 8, 7])``` => 13x12x11x10x9x8x7 = 8648640
Mi respuesta: ```[13, 11, 9, 8, 7, 5]``` => 13x11x9x8x7x5 = **360360**

Para otros valores de n, sucede lo mismo.

Estoy yo errado en el procedimiento?

**Comment by ChristYela** [comment]
Porqué está calculando el MCM usando el MCD? No logro entender esa parte, o está mal redactada la pregunta?

**Comment by ChristYela** [comment]
También tengo esa inquietud. con respecto a los factores para que den el valor esperado.

**Comment by keljozap** [comment]
Hola chicos! les comento que el ejercicio tiene varias formas de resolverse y una de ellas (que tiene que ver con una pregunta matemática) es la correcta para llegar a la totalidad de los factores. Aunque esta condición no afecta el primer valor de la respuesta (el múltiplo más pequeño) si afecta la segunda parte (los factores). Esta bien que no todos somos matemáticos puros pero busquen en internet y les aseguro que van a encontrar la razón del error.

**Comment by JonathanProf** [comment]
También tengo esa misma inquietud, porque al multiplicar los factores debería obtenerse el mismo resultado del mínimo común múltiplo de los números.

**Comment by keljozap** [comment]
La clave del ejercicio es que dice FACTORES, no dice FACTORES PRIMOS. Es una cáscara. Por eso les dije que era algo matemático. Pero que chévere @edcalderin que encontraste la solución!

**Comment by edcalderin** [comment]
Asi es @keljozap Muchas gracias!

**Comment by Elioric** [comment]
Buenas tardes, @keljozap 

Como resalta @edcalderin los números entregados en la devolución no dan como resultado el MCM. Sí se toma la definición de **factor** como un número entero que divide a un número **_x_** sin dejar residuo, o como un número **_a_** que multiplicado por un número **_b_** da como resultado el valor deseado, entonces todos los número de 1 a n son factores. Justamente por esto es el MCM de ese rango de números, porque es divisible por todos los valores evaluados.

Si lo que se desea es dividir el número de manera consecutiva, de forma descendente por el rango de números determinado, la devolución tampoco da como resultado el MCM.

Considero que el ejercicio requiere un poco más de información

**Comment by lrestrepoteck** [comment]
Hola NO entiendo por que el minimo producto es entre dos numeros y no se cual seria el segundo numero en nuestro caso.

saludos.

**Comment by Annubis1709** [comment]
Necesito ayuda. Si los factores no son los del mínimo común multiplo (LCM en inglés) entonces debo calcular los factores de qué?

**Comment by Annubis1709** [comment]
Lo de calcular el mínimo común múltiplo MCM (LCM en inglés) de los primeros n números está mas que claro para mí, pues como menciona `keljozap` es un problema matemático común. De hecho en la teoría analítica de los números se suele utilizar el algoritmo euclideano o algoritmo de euclides para calcular de manera eficiente el máximo común divisor (MCD) y a partir de este (MCD) el mínimo común múltiplo, ya que MCD y el Mínimo Común Múltiplo MCM (LCM) de dos números están relacionados entre sí.

 `a⋅b = MCD(a,b)⋅MCM(a,b)
Donde:
a y b son los dos números.
`
De hecho así resolví este punto del taller, sin embargo yo he tenido la duda en el cálculo de la lista de los factores ya que inicialmente creí que eran los factores que constituían al  mismo mínimo común multiplo calculado.  
De todas maneras yo ya lo tengo resuelto, cumpliendo con todas las condiciones (punto calificado como correcto por el bot), pero para ser sincero la lista de factores lo determiné analizando patrones que descubrí a partir de la respuesta del bot.

**Comment by keljozap** [comment]
Hola @Annubis1709 eso está muy bien! A veces para llegar a la respuesta debemos valernos de todas las herramientas a nuestra disposición y una de estas en este caso son los resultados del calificador o control. Que bueno que hayas llegado a la respuesta usando una herramienta que puede ser usada y que pocos han utilizado. Efectivamente como indicas este problema hace uso  del algoritmo euclidiano. Esta es una de las cosas que podían averiguar realizando un poco de investigación y me parece genial que nos hayas compartido tu método de análisis.

**Comment by aquirozg** [comment]
Compañero @Annubis1709 espero que estés muy bien. Una compañera y yo hemos estado luchando mucho con este punto desde la semana pasada, y no hemos podido entender cómo llegar a la lista correcta de factores. Te agradeceríamos mucho la explicación que nos puedas brindar. Gracias :)
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/124750468/ebfbc984-38e3-4a3d-b6ca-3dad8a5da965)

**Comment by Annubis1709** [comment]
Hola [aquirozg](https://github.com/aquirozg) solo tienes que imprimir la lista de forma regresiva desde `n` hasta `n // 2`. Quedo atento.

**Comment by aquirozg** [comment]
Muchas gracias @Annubis1709

**Comment by CristianMongar** [comment]
Excelente aporte @Annubis1709
