### ISSUE TITLE
Taller 3 (Condicionales) - Pregunta 11

### ISSUE THREAD

**Issue by mariafrancodev** [codingupmyfuture/bootcamplinuxpython#97]
En este punto no sé si ponerle el operador `>` o `>=`. 

Ya que dice:

> Sólo pueden entrar los ganadores que tengan la mayoría de edad

Pero luego dice:

> si son hombres deben ser mayores de 21 y si son mujeres deben ser mayores de 18

 Y no sé cómo lo tome el bot, se contradice.

**Comment by ChristYela** [comment]
Tendría que ser mayor o igual  que a las edades según el género ( así se incluyen tanto el 18 como el 21); si se deja el mayor que (a secas, se estarían excluyendo tanto el 18 como el 21); lo cual no tendría sentido . 

Una prueba de escritorio con ambos ejemplos de los que se mencionan en el enunciado para validar lo que acabo de argumentar.

**Comment by villarrealjk** [comment]
Hola @mariafrancodev y @ChristYela,

Así como dice @ChristYela el bot solo valida la expresión mayor que (a secas), deja por fuera a 18 y 21, no sé si se corregirá o lo dejarán así, miren como me calificó

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/4296845/2a3109a3-be69-4a91-a3bb-60386b222bfb)

**Comment by JoseJulianMosqueraFuli** [comment]
Hola a todos,

Quería adjuntar evidencia relacionada con una respuesta que me pareció un tanto inusual, específicamente en el caso de los valores 23, 21 y 22, donde el bot devuelve un valor False, Imagen de Kevin.

Al observar la imagen de control, es evidente que para estos mismos valores, no se muestra el mensaje que dice `"Alguien no cumple la condición de edad, no pueden entrar juntos"` el cual es el mensaje cuando es False. Sin embargo, tampoco se muestra el mensaje que dice `"Pueden pasar los tres porque cumplen la edad mínima"`. Así que no puedo asegurar que sea True. 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/56327269/6e950656-55cb-4a1e-b228-a1c6c45e8186)
**Nota**: Yo lo aborde mayor igual.😅

**Comment by EstebanaOrozco** [comment]
Hola el bot sigue calificando sin incluir el 18 o el 21, así que pongan `>` sino quieren que els califique mal 
<img width="676" alt="image" src="https://github.com/codingupmyfuture/bootcamplinuxpython/assets/46961406/3a22b027-87d6-44fa-b2f9-b6176b1c4b8c">
