### ISSUE TITLE
Taller 3 - ejercicio 2

### ISSUE THREAD

**Issue by villarrealjk** [codingupmyfuture/bootcamplinuxpython#98]
Hola profe @luisvasv-teck, creo que el enunciado de este ejercicio para la variable **_descuento_** se presta para diferentes interpretaciones, no es justo que el bot me califique mal todo el ejercicio porque espera como resultado una cosa cuando la solicitud que se hace puede ser ambigua y me refiero a que el bot esperaba el porcentaje (%) de descuento de acuerdo a la cantidad de puntos y no como tal el valor calculado del descuento (que fue lo que hice como respeusta). Lo ideal sería que el enunciado fuera más claro al momento de solicitar, por ejemplo: retornar el porcentaje de descuento a aplicar en la compra o el valor del descuento a aplicar en la compra.

![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/4296845/021cfd39-06b3-420a-a54b-b59a1edcd745)

**Comment by keljozap** [comment]
Hola @villarrealjk. El ejercicio está pidiendo que retornes 
![image](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50556684/9b2724b0-d2fd-4ee5-ae5e-3329e956906d)

Como se indica en la instrucción se está indicando que el descuento debe retornarse en cifras decimales haciendo uso de la fórmula descuento (dos decimales * 100) %. Así si los puntos son 200 el descuento a devolver es de 0.12 aplicando la fórmula. El enunciado indica el formato de la respuesta.

**Comment by villarrealjk** [comment]
Hola!! @keljozap ... No, eso es lo que pide que imprimamos y está OK dice que debe ser con dos decimales más los demás datos, lo que pide que retornemos es: **descuento, precio_final_de_compra**, que es lo que está evaluando el bot. Solo que no me hace sentido poner solo el porcentaje en la respuesta y no calcular cuanto es el valor real de ese descuento, pero bueno son interpretaciones como decía arriba.

**Comment by keljozap** [comment]
Hola @villarrealjk recuerda que este es un ejercicio de condicionales, el ejercicio solo pretende evaluar si tomaste las condiciones adecuadas en el sitio correcto, es decir, que si el cliente tiene XXX puntos SI le apliques XXX descuento SINO .... El ejercicio no busca ser preciso en el precio de compra o venta ya que esa no es la finalidad del ejercicio.

**Comment by villarrealjk** [comment]
Vale @keljozap muchas gracias por la aclaración!!
