### ISSUE TITLE
Taller 2, punto 3

### ISSUE THREAD

**Issue by manferjam0508** [codingupmyfuture/bootcamplinuxpython#99]
Buenos dias a todos:

Tengo una inquietud: en el punto 3 del taller 2, menciona el cálculo del área y el volumen de un cilindro, dan la altura, pero el valor que aparece dentro de la función que es 4, aparece como radian, de casualidad ese no es el valor del radio para calcular las fórmulas requeridas? ya que el radian al convertirse se da en grados, y el radio es un valor de superficie en cm; adjunto la imagen de referencia; de antemano gracias

![imagen](https://github.com/codingupmyfuture/bootcamplinuxpython/assets/50028974/5d4d7453-c16a-460d-a56c-49e5087fffe6)

**Comment by luisvasv-teck** [comment]
https://www.problemasyecuaciones.com/geometria3D/cilindro/calculadora-area-volumen-formulas-ejemplos-problemas.html

**Comment by SBuriticaM** [comment]
Hola, si, aunque llamaron a la variable radian, es el radio del cilindro. 

Yo ya envíe la tarea tomando ese parámetro como el radio y el bot lo calificó bien.

**Comment by RogerCardon** [comment]
Efectivamente el parámetro radian es el radio del cilindro, el cual está en unidades de longitud  o distancia (cm,m...), más no de área o superficie  (cm**2, m**2).

**Comment by manferjam0508** [comment]
De antemano, muchas gracias por sacarme de dudas, de esa manera fue que hice el cálculo tanto del volumen como del área del cilindro; ya con esto procedo a cerrar el issue.
